### ISSUE TITLE
bazel-build /sling/nlp/parser/trainer:generate-master-spec not working

### ISSUE THREAD

**Issue by emnajaoua** [google/sling#108]
I am using python2.7 in virtualenv.
in the step of running the training script : I got this error:
C++ compilation of rule '//third_party/syntaxnet:syntaxnet' failed (Exit 1)
In file included from third_party/syntaxnet/dragnn/core/interfaces/component.h:21:0,
                 from third_party/syntaxnet/dragnn/core/component_registry.h:19,
                 from third_party/syntaxnet/dragnn/core/component_registry.cc:16:
third_party/syntaxnet/dragnn/core/input_batch_cache.h:24:46: fatal error: tensorflow/core/platform/logging.h: No such file or directory
compilation terminated.
I have tried to add TENSORFLOW path variable to my bashrc file and to my virtualenv by trying those commands:
export TENSORFLOW="/home/emna/anaconda2/lib/python2.7/site-packages/tensorflow/include/:$VIRTUAL_ENV"
export TENSORFLOW="/home/emna/anaconda2/lib/python2.7/site-packages/tensorflow/include/tensorflow"
But still bazel-build doesn't find the tensorflow files in my machine while they actually exist in this repository "/home/emna/anaconda2/lib/python2.7/site-packages/tensorflow/include".
One more thing my virtualenv path is "/root/PycharmProjects/textmining/...."
Any suggestions please ?

**Comment by ringgaard** [comment]
We assume that your Python Tensorflow package is installed in /usr/local/lib/python2.7/dist-packages/tensorflow/include. This is the default location if you install it as a shared Python package. You can try to change the symbol link in third_party/tensorflow/include to /home/emna/anaconda2/lib/python2.7/site-packages/tensorflow/include.

**Comment by emnajaoua** [comment]
Thank you so much for your response.
I have did the required changes as you recommended and I have changed the  third_party/tensorflow/BUILD file. but now after running the training script, I get this error:
bazel-bin/sling/nlp/parser/trainer/generate-master-spec: error while loading shared libraries: libcublas.so.8.0: cannot open shared object file: No such file or directory.

Any ideas please ?

**Comment by ringgaard** [comment]
SLING does not directly depend on libcublas.so.8.0, but it might be Tensorflow that depends in this. Did you install the GPU version of Tensorflow? I so, you need to install the CUDA dependencies for this.

**Comment by SaiSruthiMareedu** [comment]
When I was running the steps of SLING implementation I got this error and I am not able to resolve it can you help

ERROR:
bazel-bin/sling/nlp/parser/trainer/generate-master-spec: error while loading shared libraries:  cannot open shared object file: No such file or directory.
