### ISSUE TITLE
No file system: local/sempar/commons

### ISSUE THREAD

**Issue by zuzana** [google/sling#117]
Hi, 

I'm trying to run following command from README:

```
./sling/nlp/parser/tools/train.sh --report_every=500 --train_steps=1000
```

I'm getting following error from _sling/nlp/parser/tools/train.py_:

```
INFO:tensorflow:Determining the training schedule...
INFO:tensorflow:Training schedule defined!
INFO:tensorflow:Starting training...
2017-12-18 13:08:53.942650: I third_party/syntaxnet/dragnn/core/ops/dragnn_op_kernels.cc:77] Creating new ComputeSessionPool in container handle: shared
[2017-12-18 13:08:53.945291: E ./sling/base/status.h:63] ERROR 1 : No file system: local/sempar/commons
[2017-12-18 13:08:53.945307: F sling/stream/file.cc:25] Check failed: File::Open(filename, "r", &file_) 
./sling/nlp/parser/tools/train.sh: line 259: 30661 Abort trap: 6           python sling/nlp/parser/tools/train.py --master_spec="${OUTPUT_FOLDER}/master_spec" --hyperparams="${HYPERPARAMS}" --output_folder=${OUTPUT_FOLDER} --flow=${OUTPUT_FOLDER}/sempar.flow --commons=${COMMONS} --train_corpus=${TRAIN_FILEPATTERN} --dev_corpus=${DEV_FILEPATTERN} --batch_size=${BATCH_SIZE} --report_every=${REPORT_EVERY} --train_steps=${TRAIN_STEPS} --logtostderr
```

It is failing when trying to run 

```
# Make sure to re-initialize all underlying state.
sess.run(tf.global_variables_initializer())
```
File _local/sempar/commons_ does exist in file system. 

Also the python script does not have problem reading train_corpus and dev_corpus from the same folder. 

```
# Read train and dev corpora.
print "Reading corpora..."
train_corpus = read_corpus(FLAGS.train_corpus)
dev_corpus = read_corpus(FLAGS.dev_corpus)
```

**Is there some configuration I'm missing? Or the paths to files are resolved differently somehow?**

os: Mac OS Sierra
gcc: 4.2.1
python: 2.7.1

Thanks.

**Comment by ringgaard** [comment]
The "No file system" error is usually because you have not linked in //sling/file:posix into your binary (bazel-bin/sling/nlp/parser/trainer/sempar.so?).

**Comment by zuzana** [comment]
in _sling/nlp/parser/trainer/BUILD_ I have following: 

```
cc_binary(
  name = "sempar.so",
  deps = [
    ":sempar-component",
    "//sling/base:libinit",
    "//sling/file:posix",
    "//sling/stream",
    "//third_party/syntaxnet:dragnn-ops",
  ],
  linkshared = 1,
  linkstatic = 1,
)
```

_sling/file:posix_ is listed as dependency.

Is that not enough or what else should I do to make sure that posix is linked to sempar.so binary? 

Thanks.

**Comment by ringgaard** [comment]
The basic reason for the error is probably that that File::Init() has not been called.

One issue could be that the constructor in [libinit.cc](https://github.com/google/sling/blob/master/sling/base/libinit.cc#L30) is not called when the library is loaded on MacOS. I cannot debug these issues for you on MacOS, so you are on your own in getting this to work on  MacOS.

**Comment by zuzana** [comment]
Ok, l will try to investigate further, any suggestion helps :)

**Comment by ringgaard** [comment]
I am not sure that the GCC attribute init_priority is supported on MacOS, but it looks like the constructor attribute is supported, so you could try to replace sling/base/libinit.cc with something like this:

```c++
#include "sling/base/init.h"
#include "sling/base/logging.h"

namespace sling {

#ifdef __APPLE__

__attribute__((constructor)) static void LibraryInitializer() {
  static bool initialized = false;
  if (!initialized) {
    initialized = true;
    InitSharedLibrary();
  }
}

#else

// Class for initializing program modules.
class LibraryInitializer {
 public:
  LibraryInitializer() {
    InitSharedLibrary();
  };
};

// The initialization priority should be set higher than the priority of the
// module initializers in init.h.
static LibraryInitializer init __attribute__((init_priority(2000)));

#endif

}  // namespace sling
```

**Comment by zuzana** [comment]
you were right with `File::Init()` not being called once `tf.load_op_library( ... sempar.so)` is loaded. 
The suggestion above unfortunately did not help either. 
Meanwhile I just updated `sling/file/file.cc` like this:

```
FileSystem *FindFileSystem(const string &filename, string *rest) {
  bool noDefaultFs = (default_file_system == nullptr);
  if (noDefaultFs) {
    File::Init();
  }
  // Match the first component in the path.
  if (!filename.empty() && filename[0] == '/') { 
   ... rest of the method unchanged
}
```

Not proud of it but it gets me where I need to be at the moment. 
Thanks a lot for help.

**Comment by ringgaard** [comment]
Thanks for investigating this. I have made PR #119 to add this fix. In the long run, we probably need to ensure that the module initializers are properly run on MacOS, but this will at least ensure that the file systems are initialized.
