### ISSUE TITLE
Can you provide Chinese language materials, please?

### ISSUE THREAD

**Issue by xiaozw123** [google/sling#121]
Can you provide Chinese language materials, please?

**Comment by zhenglm** [comment]
Up! 
Can you give some ideas about how to process the chinese corpous in the OntoNotes to train a parser, please?

**Comment by freefuiiismyname** [comment]
Up!
Plz.Need chinese corpus +1.

thanks:)

**Comment by ringgaard** [comment]
We don't have a conversion of the Chinese OntoNotes. We are currently using Google-internal tools for the conversion, but we are working on an open-source version of the conversion although we currently have no plans to support Chinese.

If you have access to OntoNotes, you can do the conversion yourself. First, you need to train word embeddings for Chinese in word2vec format. Then you will have to convert the annotated training and evaluation documents in OntoNotes to SLING format. You can either do this in [C++](https://github.com/google/sling#data-preparation) or you can use the [Python API](https://github.com/google/sling/issues/82#issuecomment-350237243). You then write each document to a file in a zip archive, and you can then use these for training and evaluation.

**Comment by freefuiiismyname** [comment]
thanks for your kindly reply.

**Comment by zhenglm** [comment]
Thank you very much.
