### ISSUE TITLE
Documentation would be lot clearer if frame documentation link is included in sling readme

### ISSUE THREAD

**Issue by shishircc** [google/sling#123]
I highly recommend to include  link to [documentation of frames](https://github.com/google/sling/blob/master/sling/frame/README.md) in root Sling readme file. 

Also it would be great if some API documentation of Store, Parser, ParserAction etc based on [doxyzen](http://www.stack.nl/~dimitri/doxygen/) ([javadoc](https://docs.oracle.com/javase/7/docs/api/) style) was included. It would make much clearer what's happening underneath without needing to read the c++ or header files. Let me know if I could help with these two things ? I would be glad to help. Alternatively a script to generate the doxygen output would be a good pointer. 

Present readme is great at introducing the ML portions of Sling (training, parsing, deep learning model and link to paper describing more details), while giving insufficiently high level  concept of frame and absolutely no concept around store, even though store is mentioned quite a few times it is not very clear what it is (I imagined it is a folder but turns out it is a in memory database of sorts which supports the parser).  This makes actually using it for training a new model less accessible. By including link to frames readme file in root readme and adding doxygen documentation, these would become clearer. 

I hope by improving the documentation in readme, the framework can be more accessible for more people.

**Comment by ringgaard** [comment]
Thanks for adding the link to the SLING guide. 

While we have documentation of the classes and methods in the code files, we are not using Doxygen-compatible comments for this. You should look in the code files for documentation.
