### ISSUE TITLE
Docker - which versions of c++, linux, python, tensorflow etc ?

### ISSUE THREAD

**Issue by shishircc** [google/sling#128]
I recently faced #115 and am still struggling with it. Hence questions I have is about docker to make it easy to experiment with training for sling. 

I can help to create docker image if you let me know which versions of dependencies are required. 
1. linux
2. python 
3. bazel
4. gcc
5. g++
6. tensorflow

**Comment by ringgaard** [comment]
As far as I know, we can run on any x64 version of Linux. We use Python 2.7, gcc 4.8, Tensorflow 1.4, and Bazel 0.9.0.

**Comment by shishircc** [comment]
great, thanks
