### ISSUE TITLE
One document per sentence

### ISSUE THREAD

**Issue by shishircc** [google/sling#129]
Hi, 

While creating training set, a particular text document with multiple sentences could theoretically be either converted to single sling document or multiple. 
E.g. 
Text : John went to Japan. He recommends the travel. 
Tag: Recommend(what=travel,where=japan)

How should the two separate sling documents be created in such case ?

**Comment by ringgaard** [comment]
The current parser does not support annotations that span sentences, which is a problem when annotating co-reference. We are currently working on the next generation of the parser which among other things will lift this limitation.

**Comment by shishircc** [comment]
Thanks. Looking forward to it.

**Comment by FlorianPfisterer** [comment]
I'm also interested in this feature. What's the current status? @ringgaard 
Wasn't able to find something about this in the docs.

**Comment by ringgaard** [comment]
We are working on a new version of the parser that can keep context across sentences and will also have other new features like reference and entity resolution. This is still work in progress.
