### ISSUE TITLE
Custom tokenization

### ISSUE THREAD

**Issue by shishircc** [google/sling#130]
For a text like "I recommend to buy this house between $100/$115 psf", I can tokenize this in different ways (E.g. $ 100 / $ 115  OR  $ 1 0 0 / $ 1 1 5 )

How can I customize tokenization during training and inference ?

**Comment by ringgaard** [comment]
During training we use pre-tokenized documents, so you can tokenize these the way you want. During inference, i.e. parsing, we use the tokenizer in `sling/nlp/document/text-tokenizer.h`. You can add your own TokenizerProcessor to modify the tokenization although we use LDC tokenization by default.

**Comment by shishircc** [comment]
Thanks for the quick response
