### ISSUE TITLE
Word2Vec format

### ISSUE THREAD

**Issue by shishircc** [google/sling#131]
I did training of word2vec using gensim and saved it in original binary format (using save_word2vec_format) and 200 dimension. However when I pass that as the custom embedding, the code failed with /sling/util/embeddings.cc line 47 failed  check. 

Can I use gensim or I should use the original code for word2vec ? 
Also I could not understand why is that line trying to check equality with \n ?

**Comment by ringgaard** [comment]
I haven't tried using gensim to generate the embeddings, but my understanding og the word2vec binary format is that the first line contains
```
<words> <dim>\n
```
This is followed by <words> "lines" containing:
```
<word> <binary float * dim>\n
```
The CHECK on line 47 checks that there is a newline after the binary encoded vector.

**Comment by shishircc** [comment]
thanks for the info.
