### ISSUE TITLE
bazel build conll-to-sling missing dependencies

### ISSUE THREAD

**Issue by jackxpeng** [google/sling#132]
Why do I get missing dependency errors on files in sling/nop/parser after I have put that path in the package_path?

bazel build -c opt local/conll2003:conll-to-sling --package_path=%workspace%:sling/nlp/parser/:sling --verbose_failuresINFO: Analysed target //local/conll2003:conll-to-sling (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/jack.peng/workspace/semantic/sling/sling/nlp/parser/BUILD:16:1: undeclared inclusion(s) in rule '//nlp/parser:parser-state':
this rule is missing dependency declarations for the following files included by 'nlp/parser/parser-state.cc':
  'sling/nlp/parser/parser-state.h'
  'sling/nlp/parser/parser-action.h'
Target //local/conll2003:conll-to-sling failed to build
INFO: Elapsed time: 1.406s, Critical Path: 1.24s
FAILED: Build did NOT complete successfully

**Comment by ringgaard** [comment]
Seem like we did not update the paths in conll-2003-sempar.tar.gz after we moved all the source code into the sling sub-directory. You need to update the BUILD file to:
```
package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "conll-to-sling",
  srcs = ["conll-to-sling.cc"],
  deps = [
    "//sling/base",
    "//sling/file:posix",
    "//sling/frame:store",
    "//sling/frame:serialization",
    "//sling/nlp/parser",
    "//sling/stream:file-input",
  ],
)
```
The includes in conll-to-sling.cc also need to be updated:
```
#include "sling/base/flags.h"
#include "sling/base/init.h"
#include "sling/base/logging.h"
#include "sling/frame/store.h"
#include "sling/frame/serialization.h"
#include "sling/nlp/document/document.h"
#include "sling/nlp/parser/parser.h"
#include "sling/stream/file-input.h"
```
If I make these updated, I can build it with the following command:
```
build -c opt local/conll2003:conll-to-sling
```

**Comment by ringgaard** [comment]
I have updated [conll-2003-sempar.tar.gz](http://www.jbox.dk/sling/conll-2003-sempar.tar.gz) so it builds with the new source code layout.

**Comment by jackxpeng** [comment]
Thank you.
