### ISSUE TITLE
How to create/use slot ids from python API

### ISSUE THREAD

**Issue by stefano-marchesin** [google/sling#134]
Hi, 

I was wondering if it is possible to assign or use slot ids, when using the pretrained 'sempar.flow', on a text example with the python api. If I understood correctly, the '#<int>' ids are temporary ones, which means that I cannot use them to properly reference the mentions connected with verbs.

Thanks in advance for your time

**Comment by ringgaard** [comment]
You can assign ids to frames when you create them:
```
import sling
store = sling.Store()
store.frame({"id": "myid", "a":10, "b": 20})
myid = store["myid"]
print myid.data()
```
Maybe you could give a more specific examples of what you want to do.
