### ISSUE TITLE
Frame definition not used during SLING runtime.

### ISSUE THREAD

**Issue by gopa810** [google/sling#170]
In the following program, I tried to analyse semantics of the sentence "Ted Barter likes software engineering". But in the output there is line 

        /s/document/mention: {=#7   :/s/phrase    /s/phrase/begin: 0    
                /s/phrase/length: 2    /s/phrase/evokes: {=#8     :/saft/person   } 
        }

I expect not "/saft/person" but "/toy/person" as defined at the line 23 in the program. How are used frames in the SLING? What needs to be done to get "/toy/person" for the "Ted Barter" on the output? Listing of code follows, as well as listing of output:  

## PROGRAM

	#include <string>
	#include <stdlib.h>
	#include <iostream>

	#include "sling/frame/object.h"
	#include "sling/frame/store.h"
	#include "sling/frame/serialization.h"
	#include "sling/nlp/document/document-tokenizer.h"
	#include "sling/nlp/parser/parser.h"

	int main() {

		// Load parser model.
		sling::Store commons;
		sling::nlp::Parser parser;
		parser.Load(&commons, "/tmp/sempar.flow");

		sling::Builder homer(&commons);

		homer.AddId("/en/barter");
		homer.AddIsA("/toy/person");
		homer.Add("name", "Ted Barter");
		homer.Add("/toy/person/age", 59);
		homer.AddLink("/toy/person/place", "/en/springfield");
		homer.AddLink("/toy/person/spouse", "/en/julia");
		homer.AddLink("/toy/person/child", "/en/bart");
		homer.AddLink("/toy/person/child", "/en/lisa");
		homer.AddLink("/toy/person/child", "/en/maggie");
		homer.AddLink("/toy/person/employer", "/en/snpp");

		sling::Frame barterPerson = homer.Create(); 

		commons.Freeze();

		// Create document tokenizer.
		sling::nlp::DocumentTokenizer tokenizer;

		// Create frame store for document.
		sling::Store store(&commons);

		sling::nlp::Document document(&store);

		// Tokenize text.
		string text = "Ted Barter likes software engineering";
		tokenizer.Tokenize(&document, text);

		// Parse document.
		parser.Parse(&document);
		document.Update();

		// Output document annotations.
		std::cout << sling::ToText(document.top(), 2);

	}

## OUTPUT

	{=#1 
	  :/s/document
	  /s/document/text: "Ted Barter likes software engineering"
	  /s/document/tokens: [{=#2 
		:/s/token
		/s/token/index: 0
		/s/token/text: "Ted"
		/s/token/start: 0
		/s/token/length: 3
		/s/token/break: 0
	  }, {=#3 
		:/s/token
		/s/token/index: 1
		/s/token/text: "Barter"
		/s/token/start: 4
		/s/token/length: 6
	  }, {=#4 
		:/s/token
		/s/token/index: 2
		/s/token/text: "likes"
		/s/token/start: 11
		/s/token/length: 5
	  }, {=#5 
		:/s/token
		/s/token/index: 3
		/s/token/text: "software"
		/s/token/start: 17
		/s/token/length: 8
	  }, {=#6 
		:/s/token
		/s/token/index: 4
		/s/token/text: "engineering"
		/s/token/start: 26
		/s/token/length: 11
	  }]
	  /s/document/mention: {=#7 
		:/s/phrase
		/s/phrase/begin: 0
		/s/phrase/length: 2
		/s/phrase/evokes: {=#8 
		  :/saft/person
		}
	  }
	  /s/document/mention: {=#9 
		:/s/phrase
		/s/phrase/begin: 2
		/s/phrase/evokes: {=#10 
		  :/pb/like-02
		  /pb/arg0: #8
		  /pb/arg1: {=#11 
			:/pb/engineer-01
			/pb/arg1: {=#12 
			  :/saft/other
			}
		  }
		}
	  }
	  /s/document/mention: {=#13 
		:/s/phrase
		/s/phrase/begin: 3
		/s/phrase/length: 2
		/s/phrase/evokes: #12
	  }
	  /s/document/mention: {=#14 
		:/s/phrase
		/s/phrase/begin: 4
		/s/phrase/evokes: #11
	  }
	}

**Comment by ringgaard** [comment]
I think this is because the parser model you are using (/tmp/sempar.flow) have been trained on a corpus where person mentions are evoked as /saft/person. The model does not perform entity linking, so it will not link #7 to /en/barter.

**Comment by gopa810** [comment]
"The model does not perform entity linking".... that means no model in sling performs it (not implemented in sling) or just my model and program does not do it (not set up in my app)? Have I need to retrain the model (sempar.flow)? Can I use sling for sentences longer than 5 words (and get correct document frame?)

**Comment by ringgaard** [comment]
The sempar.flow model has been trained on an extract from OntoNotes, the frame annotations will be entity mentions with entity types (e.g. /saft/person) and semantic role labeling, i.e. PropBank predicates with arguments. It has also been trained to annotate things like dates and measures.

If you want other annotations you will have to first make some training data (preferably lot of it) with the schemas and annotations you want and then train a new parser model using this training data.

You can parse sentence of any length, but since this is a learned parser model, there can be errors in the predicted annotations.

**Comment by gopa810** [comment]
I understand. Last question. What is the practical use of programmatic definition of frame. Is that used just for preparation of training data?

**Comment by jackxpeng** [comment]
I tried gopa810's code above and got no file system when loading sempar.flow. I tried it in both SEMPAR and CASPAR. The fix https://github.com/google/sling/pull/119 is in both.
Then I tried to just load the store from /tmp/commons (mode 777). Got the same error message. I'm on ubuntu 14. What can I do? Thanks.


```
	// Load parser model.
	sling::Store global;
	sling::LoadStore("/tmp/commons", &global);

sling2_caspar/sling$ bazel-bin/jack/main/predict
[2018-05-23 11:05:56.308520: E ./sling/base/status.h:62] ERROR 1 : No file system: /tmp/commons
[2018-05-23 11:05:56.308607: F sling/stream/file.cc:25] Check failed: File::Open(filename, "r", &file_) 
Aborted (core dumped)

```

**Comment by ringgaard** [comment]
You need to link with //sling/file:posix to use the standard unix file system.

**Comment by jackxpeng** [comment]
Thank you, Michael. That worked.
