### ISSUE TITLE
compilation issues of caspar

### ISSUE THREAD

**Issue by petacube** [google/sling#177]
this is mac os 10.13.4. 
compiles up to this point
ERROR: sling/sling/myelin/kernel/BUILD:34:1: C++ compilation of rule '//sling/myelin/kernel:sse' failed (Exit 1)
In file included from sling/myelin/kernel/sse.cc:15:
In file included from ./sling/myelin/kernel/sse.h:18:
In file included from ./sling/myelin/compute.h:23:
./sling/myelin/flow.h:104:1: error: redefinition of 'Traits'
TYPE_TRAIT(int64, DT_INT64);
^
./sling/myelin/flow.h:89:39: note: expanded from macro 'TYPE_TRAIT'
  template<> inline const TypeTraits &Traits<type>() { \
                                      ^
./sling/myelin/flow.h:103:1: note: previous definition is here
TYPE_TRAIT(int64_t, DT_INT64);
^
./sling/myelin/flow.h:89:39: note: expanded from macro 'TYPE_TRAIT'
  template<> inline const TypeTraits &Traits<type>() { \
                                      ^
./sling/myelin/flow.h:104:1: error: redefinition of 'Traits'
TYPE_TRAIT(int64, DT_INT64);
^
./sling/myelin/flow.h:92:39: note: expanded from macro 'TYPE_TRAIT'
  template<> inline const TypeTraits &Traits<type *>() { \
                                      ^
./sling/myelin/flow.h:103:1: note: previous definition is here
TYPE_TRAIT(int64_t, DT_INT64);
^
./sling/myelin/flow.h:92:39: note: expanded from macro 'TYPE_TRAIT'
  template<> inline const TypeTraits &Traits<type *>() { \
                                      ^
2 errors generated.
INFO: Elapsed time: 29.437s, Critical Path: 10.66s
INFO: 49 processes, local.
FAILED: Build did NOT complete successfully

The most similar command is
	branch
 git branch
* caspar
  master

**Comment by ringgaard** [comment]
We do not really support MacOS since we do not have access to a Mac build environment, so I cannot debug this issue, but if it is something trivial that needs to be fixed to make it build on MacOS, I would be happy to include this fix.

What version of gcc are you using?

**Comment by petacube** [comment]
i am not sure it mac-specific. its c++ issue with the code. 

 gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix

**Comment by ringgaard** [comment]
I agree. This looks more like a compiler issue than an os issue. I looks like you are using clang. We usually use GCC, so the code has not been tested for compilation with clang.

It looks like you can switch between compilers by setting the CC variable:
```
CC=/usr/bin/gcc tools/buildall.sh
CC=/usr/bin/clang tools/buildall.sh
```
I tried this, and it looks like we need to fix a number of issues to make it build with clang. In the meantime you can consider using gcc for compiling.

**Comment by ringgaard** [comment]
I have submitted #178 which fixes a number of issues to make it possible to build SLING using clang. This particular clang build error is because int64_t and int64 were the same type. I have changed the int types in sling/base/types.h to use the type definitions from stdint.h to make it more portable.

**Comment by petacube** [comment]
ok that error went away
a new one is 
bazel build -c opt sling/nlp/parser sling/nlp/parser/tools:all

1 warning generated.
ERROR: sling/third_party/jit/BUILD:37:1: C++ compilation of rule '//third_party/jit:cpu' failed (Exit 1)
third_party/jit/cpu.cc:32:10: fatal error: 'sys/sysinfo.h' file not found
#include <sys/sysinfo.h>

**Comment by petacube** [comment]
both of errors i had reported  seems be linux specifc 
elf defined binary execution format and sysinfo is proces control.

**Comment by ringgaard** [comment]
I have made a patch for these two Linux-specific issues. Since I don't have access to a Mac OSX build environment, I will have to rely on you to test this out. Please let me know id this patch works:

```
diff --git a/sling/myelin/analyze.cc b/sling/myelin/analyze.cc
index 43bac96..79b8e6f 100644
--- a/sling/myelin/analyze.cc
+++ b/sling/myelin/analyze.cc
@@ -45,13 +45,16 @@ DEFINE_string(graph, "", "DOT file name for flow");
 DEFINE_bool(consts, true, "Include constants in DOT graph");
 DEFINE_string(datagraph, "", "DOT file name prefix for data profile");
 DEFINE_int32(batch, 1, "Batch size");
-DEFINE_string(o, "", "ELF object output file for generated code");
-DEFINE_bool(gendata, false, "Output tensor data to ELF object file");
-DEFINE_bool(genrwdata, false, "Allocate space for tensor data in object file");
 DEFINE_bool(gpu, false, "Run kernels on GPU");
 DEFINE_bool(argmax, false, "Use argmax for predictions");
 DEFINE_bool(compile, true, "Compile flow");
 
+#ifdef __linux__
+DEFINE_string(o, "", "ELF object output file for generated code");
+DEFINE_bool(gendata, false, "Output tensor data to ELF object file");
+DEFINE_bool(genrwdata, false, "Allocate space for tensor data in object file");
+#endif  // __linux__
+
 using namespace sling;
 using namespace sling::myelin;
 
@@ -148,12 +151,13 @@ int main(int argc, char *argv[]) {
   if (FLAGS_compile && !FLAGS_raw) {
     // Compile model.
     LOG(INFO) << "Compiling flow";
-    ElfLinker *linker = nullptr;
     Network network;
     if (FLAGS_gpu) {
       cudart.Connect();
       network.set_runtime(&cudart);
     }
+#ifdef __linux__
+    ElfLinker *linker = nullptr;
     if (!FLAGS_o.empty()) {
       ElfLinker::Options linker_opts;
       if (FLAGS_gendata) linker_opts.generate_data = true;
@@ -164,6 +168,7 @@ int main(int argc, char *argv[]) {
       linker = new ElfLinker(linker_opts);
       network.set_linker(linker);
     }
+#endif  // __linux__
     if (FLAGS_profile) network.options().profiling = true;
     if (FLAGS_dynalloc) network.options().dynamic_allocation = true;
     if (!network.Compile(flow, library)) {
@@ -198,6 +203,7 @@ int main(int argc, char *argv[]) {
       }
     }
 
+#ifdef __linux__
     // Write ELF object file. The file can be viewed with objdump:
     // objdump -xrtdw -M intel --no-show-raw-insn <ofn>
     if (linker != nullptr) {
@@ -207,6 +213,7 @@ int main(int argc, char *argv[]) {
     }
     delete linker;
   }
+#endif  // __linux__
 
   return 0;
 }
diff --git a/sling/util/elf-writer.cc b/sling/util/elf-writer.cc
index 72ef0c1..8a7c572 100644
--- a/sling/util/elf-writer.cc
+++ b/sling/util/elf-writer.cc
@@ -14,6 +14,8 @@
 
 #include "sling/util/elf-writer.h"
 
+#ifdef __linux__
+
 #include <elf.h>
 #include <string.h>
 #include <stdio.h>
@@ -293,3 +295,5 @@ void Elf::Buffer::Update() {
 
 }  // namespace sling
 
+#endif  // __linux__
+
diff --git a/sling/util/elf-writer.h b/sling/util/elf-writer.h
index 00e36f4..cb4f761 100644
--- a/sling/util/elf-writer.h
+++ b/sling/util/elf-writer.h
@@ -15,6 +15,8 @@
 #ifndef SLING_UTIL_ELF_WRITER_
 #define SLING_UTIL_ELF_WRITER_
 
+#ifdef __linux__
+
 #include <elf.h>
 #include <stdint.h>
 #include <stdio.h>
@@ -140,4 +142,6 @@ class Elf {
 
 }  // namespace sling
 
+#endif  // __linux__
+
 #endif  // SLING_UTIL_ELF_WRITER_
diff --git a/third_party/jit/cpu.cc b/third_party/jit/cpu.cc
index 5d89a44..d76f05e 100644
--- a/third_party/jit/cpu.cc
+++ b/third_party/jit/cpu.cc
@@ -29,9 +29,6 @@
 // modified significantly by Google Inc.
 // Copyright 2017 Google Inc. All rights reserved.
 
-#include <sys/sysinfo.h>
-#include <utility>
-
 #include "third_party/jit/cpu.h"
 
 #include "sling/base/logging.h"
@@ -315,11 +312,31 @@ void CPU::Initialize() {
   }
 }
 
+#if defined( __linux__)
+#include <sys/sysinfo.h>
+
 int CPU::Processors() {
-  Probe();
   return get_nprocs();
 }
 
+#elif defined(__APPLE__)
+#include <sys/sysctl.h>
+
+int CPU::Processors() {
+  int cpus = 1;
+  size_t len = sizeof(cpus);
+  sysctlbyname("hw.logicalcpu", &cpus, &len, nullptr, 0);
+  return cpus;
+}
+
+#else
+
+int CPU::Processors() {
+  return 1;
+}
+
+#endif
+
 }  // namespace jit
 }  // namespace sling
 ```

**Comment by ringgaard** [comment]
I got an OSX build environment up and running, and I have managed to get the parser and the Python API to build under OSX. The code currently live in my dev branch, so could I get you to check if this works for you?
```
git clone https://github.com/ringgaard/sling.git sling-ringgaard
cd sling-ringgaard
git checkout dev
bazel build -c opt sling/pyapi:* sling/nlp/parser/tools:*
```
Not all the components can build under OSX. The ELF file output from Myelin and embed_data are not supported under OSX. These would need to write Mach-O files instead of ELF files. Also, the HTTP server uses epoll which is not supported by OSX. I have disabled the task dashboard under OSX, but you can still run the wiki processing tasks.
