### ISSUE TITLE
CASPAR Myelin guide, can't import FlowBuilder

### ISSUE THREAD

**Issue by jackxpeng** [google/sling#186]
I'm following the Myelin guide for CASPAR at https://github.com/google/sling/blob/caspar/doc/guide/myelin.md but can't import FlowBuilder.

I can do "from builder import Builder" instead. Should the doc be updated or am I doing something wrong? Thanks.

**Comment by ringgaard** [comment]
Looks like we forgot we forgot to update the Myelin documentation when submitting #184 where we switched to the new version of the flow builder which is used by the pytorch-based trainer. Thanks for reporting this.

I have updated the documentation in #185 and also added an `__init__.py` file to the myelin package. The` FlowBuilder` class has been renamed to Builder so the `Flow` and `Builder` can now be imported from the `sling.myelin` package:
```
from sling.myelin import Flow
from sling.myelin import Builder
```

**Comment by jackxpeng** [comment]
Somehow the imports don't work for me. Do you mean the python.myelin package? I tried that and got an error about PhraseTable.

```
sling$ python -c "from sling.myelin import Flow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named myelin
```
```
sling$ python -c "from python.myelin import Flow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "python/__init__.py", line 12, in <module>
    PhraseTable=api.PhraseTable
AttributeError: 'module' object has no attribute 'PhraseTable'

```

**Comment by ringgaard** [comment]
Could this be because you are missing the symbolic link described in the [installation guide](https://github.com/google/sling/blob/caspar/doc/guide/install.md)?
```
git checkout caspar
bazel build -c opt sling/pyapi:pysling.so
sudo ln -s $(realpath python) /usr/lib/python2.7/dist-packages/sling
```

**Comment by jackxpeng** [comment]
You are right, Michael. I missed that step. Thank you.
