### ISSUE TITLE
from task import * inside task directory

### ISSUE THREAD

**Issue by jackxpeng** [google/sling#187]
https://github.com/google/sling/blob/caspar/python/task/__init__.py
from task import *
This is causing "no module named task" errors.

Seems like this line should be removed because there is no task inside the task directory.

**Comment by ringgaard** [comment]
Oops. That's a bug. I've made #188 to fix this. I found out that the reason I did not get this error was because workflow.py was named task.py in an earlier version of the code, and I still had the task.pyc file in the task directory, which masked the problem. Thanks for reporting this.

**Comment by jackxpeng** [comment]
Thank you for fixing this, Michael.
