### ISSUE TITLE
F1 Score of individual entities 

### ISSUE THREAD

**Issue by kritisinghal2211** [google/sling#202]
How do I calculate the F1-score of individual entities evoked in mentions. 
Say it can evoke three types of entities, A, B and C (in the eg, it evokes A); how can I calculate individual F1-score of A, B and C.
/s/document/mention:
 { :/s/phrase
 /s/phrase/begin: 70 
/s/phrase/length: 3 
/s/phrase/evokes:
     { :/entity/A} }

**Comment by ringgaard** [comment]
The evaluation procedure we use for computing the F1 scores is described in Section 8 of the [SLING paper](https://arxiv.org/pdf/1710.07032.pdf). You can also check the [frame evaluation code](https://github.com/google/sling/blob/master/sling/nlp/parser/trainer/frame-evaluation.h) for the details. We do not currently compute F1 scores individually for each evoked frame type. If you want to do this, you basically need to make a `Benchmark` object for each frame type and compute the precision and recall for each golden type.

**Comment by kritisinghal2211** [comment]
Hi, Thank you for your help. It worked out well!

**Comment by satya-323** [comment]
Hi, can you give an example on what changes need to be made in the code to find out the evaluation metric regarding a particular frame?
