### ISSUE TITLE
modify schema for learning more information

### ISSUE THREAD

**Issue by cklckl** [google/sling#208]
if it possible to add something like speech act in SLING document schema?
maybe like:
{=#1
    :/s/document
    /s/document/text: "example sentence"
    **/s/document/speechact: "tell"**
    /s/document/tokens: [{=#2
    ....
    ....
}

it seem that i should modify something like document reading ?
And if there are any example for "role: {=/s/document/theme" in document schema?
Thanks for the help!

**Comment by johndpope** [comment]
From my understanding, looking at diagram
https://ai.googleblog.com/2017/11/sling-natural-language-frame-semantic.html
SLING connects the VERB and EVENT frames using the role ARG1

And glancing at docs
 _the real power of DRAGNN is the ability of one Component to learn representations that are useful for downstream Components.(ARG1?)  As each Component iterates over the data, it writes intermediate representations to a tf.TensorArray object. Downstream Components can then read the representations populated by upstream ones. During training, errors are back-propagated from downstream Components to tune the representations from upstream ones. This process is called stack-propagation._

from diving into whitepaper 
https://arxiv.org/pdf/1603.06598.pdf
Traditional syntax models typically leverage part-of-speech (POS) information by
constructing features from hand-tuned templates. We demonstrate that a better
approach is to utilize POS tags as a **regularizer** of learned representations. We
propose a simple method for learning a stacked pipeline of models which we call
“stack-propagation.” 
<img width="676" alt="screen shot 2018-07-03 at 8 07 41 pm" src="https://user-images.githubusercontent.com/289994/42250085-c5319d24-7efc-11e8-8f44-b74e22850ec0.png">


Does that mean sling uses Parts Of Speech tags as regularizer for it's learned representations too?
would that correspond to verbs / nouns....if so - which step / line of code would this correspond to ?

**Comment by ringgaard** [comment]
SLING does not use POS tags for parsing. The parser model is learned directly from the words. However, the words are mapped through (pre-trained) word embeddings, which would probably put words with the same POS closer together. Also, the bi-lstms would be able to learn representations of the words in context. In my experience, the continuous representation that we can learn during training works better than any hand annotated immediate representations.

For the OntoNotes corpus, we have golden POS tags, so we could in principle use these, either as input features, or as a regularizer as you mention. However, we have not done any experiments with that.
