### ISSUE TITLE
ERROR 404: Is caspar.flow available?

### ISSUE THREAD

**Issue by lenyabloko** [google/sling#215]
Hi there, 

I am trying to use SLING 2.0.0 but cant get caspar.flow 

:~$ wget http://www.jbox.dk/sling/caspar.flow
--2018-07-19 03:55:04--  http://www.jbox.dk/sling/caspar.flow
Resolving www.jbox.dk (www.jbox.dk)... 93.166.244.18
Connecting to www.jbox.dk (www.jbox.dk)|93.166.244.18|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-07-19 03:55:05 ERROR 404: Not Found.

**Comment by ringgaard** [comment]
We are still working on the final details of the CASPAR parser, so we have not yet released a pre-trained model.
