### ISSUE TITLE
TORCH : is not a supported wheel

### ISSUE THREAD

**Issue by lenyabloko** [google/sling#216]
Hi.,
What do I need to load torch?

(python2.7) lenyabloko@thinker:~$ sudo pip install http://download.pytorch.org/whl/cpu/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl
torch-0.3.1-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by johndpope** [comment]
![screen shot 2018-07-19 at 9 53 19 am](https://user-images.githubusercontent.com/289994/42946715-97d006b0-8b39-11e8-94b3-20c8fc4e390f.png)

use (+ ❤️) conda 
https://pytorch.org/

**Comment by johndpope** [comment]
this is not an issue specific to sling so should be closed. stackoverflow is best place for this
