### ISSUE TITLE
Check failed: input_.size() >= sizeof(FileHeader) 

### ISSUE THREAD

**Issue by lenyabloko** [google/sling#233]
Hi. getting the same error as reported in #226 

[2018-08-21 17:57:12.108589: I sling/task/job.cc:400] Task fused-items/sharder done
[2018-08-21 17:57:12.173354: I sling/task/job.cc:395] Task fused-items/record-file-reader[4/11] completed
[2018-08-21 17:57:13.731435: F sling/file/recordio.cc:170] Check failed: input_.size() >= sizeof(FileHeader) (0 vs.
 24) Record file truncated: /tmp/local.5JyBY1/00008
./run.sh: line 3:  6543 Aborted   

Steps to recreate:
./run.sh --download_wikidata

 check the md5 hash to match the source
/sling/local/data/corpora/wikidata$ md5sum wikidata-20180806-all.json.bz2
9270f40071a270cfcefb823af02aeb18  wikidata-20180806-all.json.bz2

./run.sh --download_wikipedia
~/sling/local/data/corpora/wikipedia$ md5sum enwiki-20180801-pages-articles.xml.bz2
02b51be5d4af70124fa3d07578ff82da  enwiki-20180801-pages-articles.xml.bz2

./run.sh --import_wikidata
.Done
~/sling/local/data/e/wiki$ ls -l
total 11893804
drwxr-xr-x 2 nineldynov nineldynov       4096 Aug 21 09:37 en
-rw-r--r-- 1 nineldynov nineldynov    1048182 Aug 21 10:23 properties.rec
-rw-r--r-- 1 nineldynov nineldynov 1217393941 Aug 21 11:50 wikidata-items-00000-of-00010.rec
-rw-r--r-- 1 nineldynov nineldynov 1217393870 Aug 21 11:50 wikidata-items-00001-of-00010.rec
-rw-r--r-- 1 nineldynov nineldynov 1217394615 Aug 21 11:50 wikidata-items-00002-of-00010.rec
-rw-r--r-- 1 nineldynov nineldynov 1218443008 Aug 21 11:50 wikidata-items-00003-of-00010.rec
-rw-r--r-- 1 nineldynov nineldynov 1218442018 Aug 21 11:50 wikidata-items-00004-of-00010.rec
-rw-r--r-- 1 nineldynov nineldynov 1217394218 Aug 21 11:50 wikidata-items-00005-of-00010.rec
-rw-r--r-- 1 nineldynov nineldynov 1217394355 Aug 21 11:50 wikidata-items-00006-of-00010.rec
-rw-r--r-- 1 nineldynov nineldynov 1218442993 Aug 21 11:50 wikidata-items-00007-of-00010.rec
-rw-r--r-- 1 nineldynov nineldynov 1217394663 Aug 21 11:50 wikidata-items-00008-of-00010.rec
-rw-r--r-- 1 nineldynov nineldynov 1218443289 Aug 21 11:50 wikidata-items-00009-of-00010.rec

./run.sh --import_wikipedia
...
[2018-08-21 15:02:06.387987: I run.py:237] Done

:~/sling$ ./run.sh --parse_wikipedia
.....
[2018-08-21 16:52:09.421441: I sling/task/job.cc:412] Stage #1 done
[2018-08-21 16:52:10.565639: I workflow.py:688] sending final status to monitor
[2018-08-21 16:52:10.566054: I run.py:237] Done

~/sling$ ./run.sh --merge_categories
....
[2018-08-21 17:09:54.822401: I workflow.py:688] sending final status to monitor
[2018-08-21 17:09:54.822679: I run.py:237] Done

~/sling$ ./run.sh --fuse_items
....
[2018-08-21 17:57:12.108589: I sling/task/job.cc:400] Task fused-items/sharder done
[2018-08-21 17:57:12.173354: I sling/task/job.cc:395] Task fused-items/record-file-reader[4/11] completed
[2018-08-21 17:57:13.731435: F sling/file/recordio.cc:170] Check failed: input_.size() >= sizeof(FileHeader) (0 vs. 24) Record file truncated: /tmp/local.5JyBY1/00008
./run.sh: line 3:  6543 Aborted

**Comment by ringgaard** [comment]
Did you check if you ran out of disk space for your tmp dir? 
The error indicates that the file is empty. Is /tmp/local.5JyBY1/00008 or any of the other files in this directory empty?

The fuse-items stage fuses wikidata-items (15 GB) with wikipedia-items (387 MB), so you need at least this much space in your temp dir to merge them.

The weird thing is that you seem to get the error when trying to [read the merge files](https://github.com/google/sling/blob/caspar/sling/task/sorter.cc#L180) where I would expect you to get the error when [writing them](https://github.com/google/sling/blob/caspar/sling/task/sorter.cc#L136).

Could I get you to run the fuse-items task with extended logging and send the output of this?
```
./run.sh --fuse_items --v=3
```

**Comment by ringgaard** [comment]
Could it be that you ran out of memory? The kb-builder needs lot of RAM. I think you need at least 32GB RAM.

**Comment by lenyabloko** [comment]
Yes, I only got 16GB RAM. I got this on --parse_wikipedia

./run.sh: line 3:  5773 Killed      

I will add more RAM and try again

**Comment by ringgaard** [comment]
The "Unexpected page: 3" message is due to an error in WikiData. I have fixed WikiData item [Q14946195](https://www.wikidata.org/wiki/Q14946195).

**Comment by lenyabloko** [comment]
With more RAM it went through all stages without errors. After that I tried to start knowledge-service

bazel-bin/sling/nlp/kb/knowledge-server
[2018-08-24 01:52:45.439180: I sling/nlp/kb/knowledge-server.cc:31] Start HTTP server on port 8080
[2018-08-24 01:52:45.439470: I sling/nlp/kb/knowledge-service.cc:67] Loading knowledge base from local/data/e/wiki/kb.sling
[2018-08-24 01:53:47.663011: F sling/frame/store.cc:72] Check failed: base_ != nullptr || bytes == 0 
Aborted

Should I open a new ticket for that?

Thank you for helping!

**Comment by ringgaard** [comment]
If you look at the code [here](https://github.com/google/sling/blob/caspar/sling/frame/store.cc#L72), this error happens if memory allocation fails, probably because you have run out of memory. Loading the knowledge base needs something like 8-10 GB RAM.

**Comment by lenyabloko** [comment]
Yes, with 32G of RAM there is no problem staring knowledge-server.
But  only 16G enough  for Python API to load kb.sling and  name-table.repo 
Thanks again
