### ISSUE TITLE
Version for Windows 10 and Python 3.6.5 and Tensorflow 1.8.0?

### ISSUE THREAD

**Issue by catskillsresearch** [google/sling#255]
This code seems to be Linux and Python 2.7.  It uses Python and TensorFlow, I have Python 3.6.5 and Tensorflow-gpu 1.8.0.  Could you please provide a version of Sling which is compatible and doesn't care whether it is on Windows or Linux?

**Comment by anders-sandholm** [comment]
Thanks for your interest in SLING, @catskillsresearch. 
While we would love to see SLING run on more platforms, we currently only provide support for Linux and Python 2.7. We don't have any current plans to provide support for Windows.
