### ISSUE TITLE
Needed guideline: Using emb-vectors on input

### ISSUE THREAD

**Issue by gopa810** [google/sling#265]
I would need to omit using word IDs, suffix IDs and word features and insert embedding vector directly to the input of LSTMs. Can you guide me where to change and what? Should I use FixedFeature or LinkedFeature for this purpose?

**Comment by ringgaard** [comment]
Which version of SLING are you using? The SEMPAR version in the main branch, or the new CASPAR version in the caspar branch?

**Comment by gopa810** [comment]
> Which version of SLING are you using? The SEMPAR version in the main branch, or the new CASPAR version in the caspar branch?

SEMPAR

**Comment by ringgaard** [comment]
SEMPAR is using the Dragnn framework, and it only support discrete features out of the box. However, if your embedding vectors are word-based, you could use these to initialize the pretrained embeddings and disable the other lexical features.

We are about to deprecate SEMPAR at the moment, and make CASPAR the main branch. CASPAR is using PyTorch, so it is easier to modify the code to support input using embedding vectors. Basically you will get rid of the features part of the network and input the embedding vectors directly into the LSTM.

**Comment by gopa810** [comment]
Thanks.
