### ISSUE TITLE
Unable to import SLING on WSL after building

### ISSUE THREAD

**Issue by SasCezar** [google/sling#291]
Hi,

I was tring to install/build SLING on Windows Subsystem Linux. 
I tried different Ubuntu versions on WSL with different GCC:

- Ubuntu 18.04 LTS GCC  7.3.0
- Ubuntu 16.04 LTS GCC 5.4.0

This is the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/sling/__init__.py", line 1, in <module>
    import pysling as api
ImportError: /usr/lib/python2.7/dist-packages/sling/pysling.so: cannot enable executable stack as shared object requires: Invalid argument
```

Fixed using the solution from: 
https://github.com/Microsoft/WSL/issues/916#issuecomment-365898305

Note that on another machine with WSL the installation went fine without the need to use the fix.

**Comment by ringgaard** [comment]
From the description of the fix, it seems like pysling.so get build with requiring executable stacks in the PT_GNU_STACK program header entry. This might depend on the version of GCC used for building. The code in pysling.so don't need executable stacks, so disabling this with the execstack utility should not be a problem. You can disable the executable stacks using the `-z noexecstack` GCC flag.
