### ISSUE TITLE
Make HTTP Server to use libevent

### ISSUE THREAD

**Issue by kiril-me** [google/sling#301]
One of the reasons SLING doesn't work on OSX is epoll support (https://github.com/google/sling/issues/189).

To make HTTP server platform independent, SLING can use libevent (https://github.com/libevent/libevent). Also, libevent has HTTP server functionality and helps decrease http-server logic.

I can work on implementation if you don't have any concerns. Libevent has BSD licence.

**Comment by anders-sandholm** [comment]
@kiril-me -- thanks for taking an interest in SLING and for filing the issue.

It sounds like a viable way to get closer to SLING working on OSX. While it would be exciting to see things run on OSX, for now, we won't have the resources needed to maintain a version with additional dependencies like libevent and maintaining support for OSX.

If you want to maintain an OSX version of SLING, an option would be for you to clone the repo to get libevent on SLING to work there. However, we can not promise you that we will backport these changes into the main repo.

**Comment by johndpope** [comment]
I think efforts should be directed to use docket - need to expose a robust api
This repo has docker and uses zeromq for communication. 
I looked into grpc with this library but it’s not ready yet.
https://github.com/hanxiao/bert-as-service
