### ISSUE TITLE
Unknown entity type: {=#1 entity-type: "sense" _id: "L29259-S2"}

### ISSUE THREAD

**Issue by hadfield** [google/sling#309]
I get the following error:

 F sling/nlp/wiki/wikidata-converter.cc:380] Unknown entity type: {=#1 entity-type: "sense" _id: "L29259-S2"}

when running:
./run.sh --build_wiki  --wikipedia 20181120 --wikidata 20181203

after successfully running:

./run.sh --download_wikidata --download_wikipedia --wikipedia 20181120 --wikidata 20181203

The default dataset is no longer available from wikipedia/data.

**Comment by ringgaard** [comment]
It seems like we are now seeing references to senses for lexemes. I will send out a fix to handle this.

**Comment by hadfield** [comment]
great!

**Comment by ringgaard** [comment]
I've made a fixed this in PR #310, which has now been submitted to the main branch.

**Comment by hadfield** [comment]
this resolved the issue on my end, thanks!

**Comment by hadfield** [comment]
I would suggest changing the default wiki datasets to a date that is available.

**Comment by anders-sandholm** [comment]
Agree. Will update the default wiki datasets. Seems we need to increase the frequency of updating the default datasets. FWIW, we had originally planned on doing this quarterly, but that is clearly not sufficient.

**Comment by anders-sandholm** [comment]
@hadfield - we've now changed the flow so that we always fetch the latest version of the dump files by default. HTH.

**Comment by hadfield** [comment]
great!  i noticed that wikidata and wikipedia are not always in sync -- i would suggest getting whatever the earlier date is (so both are available).
