### ISSUE TITLE
LABEL_* scores are 0 when training Ontonotes

### ISSUE THREAD

**Issue by SasCezar** [google/sling#323]
Hi,

I'm trying to train a parser using the Ontonotes dataset, and the scripts provided in the Ontonotes folder. While the model trains,  all measures are computed and have good values, except for the LABEL_* measures, which are all 0.

The only changes that i made to the code are to the embeddings used. I re-wrote the embedding loading function to allow for fastText embeddings.

I'm using the master branch updated to commit: [18f0b22b8a4ec576b158bf6eeab69f814ea55b81](https://github.com/google/sling/commit/18f0b22b8a4ec576b158bf6eeab69f814ea55b81)

**Comment by rahul1980** [comment]
LABEL accuracy measures how well we can predict secondary types of frames. For example if the span "1984" is labeled as a frame that evokes both DATE and NUMBER (where NUMBER is the secondary type), then LABEL would measure if we can predict NUMBER or not.

In the new Ontonotes corpus, we directly import the golden annotations, which are guaranteed to be non-overlapping, therefore a span like "1984" would only have one type. Thus LABEL accuracy doesn't apply here and will always be zero.

This is mostly an artifact of the previous Ontonotes corpus we used, which had overlapping annotations.
