### ISSUE TITLE
Parsing sentences with the python API

### ISSUE THREAD

**Issue by twoertwein** [google/sling#334]
I want to use sling to get a propbank-like parse of a sentence. [parsing.md](https://github.com/google/sling/blob/master/doc/guide/parsing.md) shows an example were 'John loves Mary' is nicely parsed (/pb/love-01, arg0, and arg1 are detected). I struggle to re-create this example with the python API using the per-trained caspar model (/pb/love-01 is not detected).

``` py
import sling

parser = sling.Parser('caspar.flow')
text = 'John loves Mary'
doc = parser.parse(text)
print doc.frame.data(pretty=True)

# prints
{=#1 
  :document
  text: "John loves Mary"
  tokens: [{=#2 
    start: 0
    size: 4
  }, {=#3 
    start: 5
    size: 5
  }, {=#4 
    start: 11
    size: 4
  }]
  mention: {=#5 
    begin: 0
    evokes: {=#6 
      :thing
    }
  }
  mention: {=#7 
    begin: 1
    evokes: {=#8 
      :/pb/predicate
      /pb/ARG0: #6
      /pb/ARG1: {=#9 
        :thing
      }
    }
  }
  mention: {=#10 
    begin: 2
    evokes: #9
  }
}
```

**Comment by rahul1980** [comment]
The Caspar model collapses all predicates to /pb/pred since we didn't have a use-case for it, and even the CONLL SRL evals didn't require it. It also gave a tremendous speedup since the softmax layer was >4x smaller. The Caspar model also uses a slew of other changes (e.g. different model architecture, numerous improvements to Myelin, and also a new way of generating training data from Ontonotes v5).

If you wish to get the original functionality, you can use the original model tagged as v1.1.0
(https://github.com/google/sling/releases/tag/v1.1.0). But please be aware that this release is no longer maintained since Caspar has diverged a lot from it.

**Comment by twoertwein** [comment]
ok, thank you for that information!

**Comment by twoertwein** [comment]
@rahul1980 do you have recommendations how parse the graphical structured from the parser output (except parsing the string itself)?

I can enumerate all annotated phrases and their slots but I haven't found a way to 'resolve' the references in the slots (sorry, I'm probably not using the terminology correctly). Let me demonstrate that at the "John loves Mary" example: doc.frame.data(pretty=True) contains the information to resolve '/pb/ARG0: # 6' since it was defined in a previous 'mention'. When I use the API:

```py
import sling

parser = sling.Parser('caspar.flow')
text = 'John loves Mary'
doc = parser.parse(text)
#print doc.frame.data(pretty=True)

for m in doc.mentions:
    print 'phrase:', doc.phrase(m.begin, m.end)
    print 'slots:', [slot for slot in m.evokes()]

# prints
phrase: John
slots: [{=#1 :thing}]
phrase: loves
slots: [{=#1 :/pb/predicate /pb/ARG0: {=#2 :thing} /pb/ARG1: {=#3 :thing}}]
phrase: Mary
slots: [{=#1 :thing}]
```
I haven't found a way to further inspect the sling.Frame object (slots[0]) to resolve to what phrase  it points (e.g., how do I connect '/pb/ARG0: {=#2 :thing}' with 'James' using the API).

**Comment by rahul1980** [comment]
The functionality to go from frames to mentions is there in the [C++ API](https://github.com/google/sling/blob/7c53dec1879c08e692389bc183b6115873a55b23/sling/nlp/document/document.h#L374), but not in the Python API, but is fairly easy to do. All that you have to build is a mapping from frames to mention(s) that evoke them.

```
from collections import defaultdict

mapping = defaultdict(list)   # Frame -> Mention(s) that evoke it
for mention in doc.mentions:
   for frame in mention.evokes():
      mapping[frame].append(mention)

predicate_frame = ...    # /pb/predicate frame
arg0 = predicate_frame["/pb/ARG0"]
mention_arg0 = mapping[arg0][0] if arg0 in mapping else None
print doc.phrase(mention_arg0.begin, mention_arg0.end)  # Should print John
```

**Comment by twoertwein** [comment]
thank you so much!

**Comment by chingting** [comment]
When I ran it, is said "AttributeError: module 'sling' has no attribute 'Parser'". Does anyone know how to fix it? I already did wget http://www.jbox.dk/sling/caspar.flow

**Comment by ringgaard** [comment]
Can you provide some more information on how to reproduce this problem?

We have recently switched to Python 3, so please sync to the latest version (and run `./setup.sh`).

**Comment by chingting** [comment]
Hi!

I just did it step by step by following the instructions on github.
I've done these 2 below, but when I tried to import sling, parser =
sling.Parser("caspar.flow"), the error came out and said sling has no
parser.

sudo pip3 install
http://www.jbox.dk/sling/sling-2.0.0-cp35-none-linux_x86_64.whl


wget http://www.jbox.dk/sling/caspar.flow

**Comment by chingting** [comment]
I did it on my ubuntu from Virtual Machine. My python version is 3.7.0.
Thank you :)

**Comment by ringgaard** [comment]
Did you download the source code as well, i.e. `git clone git@github.com:google/sling.git`? In that case you  need to run the `setup.sh` script to use the development version of SLING. What is the output if you do the following:
```
python3 -c "import sling; print(vars(sling))"
```
The problem could be that if your current directory has a sling subdirectory, you could end up with an [implicit namespace](https://www.python.org/dev/peps/pep-0420/#specification) sling package in Python 3.

**Comment by chingting** [comment]
Here is the output:

{'__name__': 'sling', '__doc__': None, '__package__': 'sling',
'__loader__': <_frozen_importlib_external._NamespaceLoader object at
0x7f90bed0c7f0>, '__spec__': ModuleSpec(name='sling',
loader=<_frozen_importlib_external._NamespaceLoader object at
0x7f90bed0c7f0>,
submodule_search_locations=_NamespacePath(['/home/ellen/sling'])),
'__file__': None, '__path__': _NamespacePath(['/home/ellen/sling'])}

Yeah I did git and script today, but still not working.

**Comment by ringgaard** [comment]
There are two basic ways to use the SLING Python API:
1. SLING user mode
2. SLING developer mode.

In _SLING user mode_, you use pip3 and install the wheel. That installs the SLING files in the Python site packages directory (normally `/usr/lib/python3/dist-packages/sling`). No other files are needed for this to work (besides the flow file used by the parser).

It is simple to install SLING using pip3, but if you are a developer and want to modify the SLING code base, it is slow to have to build the code, make a new wheel, and then install the when using pip3, so we also have a _SLING developer mode_, where you clone the git repo and run `./setup.sh`. This will install all the stuff that is needed to build SLING from source code, and then compile the SLING source code, which produces `pysling.so`. The `setup.sh` script also adds a symlink to your Python site packages directory to the python subdirectory in the git repo directory. The python subdirectory then contains a symlink to pysling.so in the bazel-bin directory. This allows you to modify the code, run `tools/buildall.sh` and then `import sling` will automagically use the newly built code.

Your SLING package path is /home/ellen/sling, which probably means that the sling package is an implicit namespace package, which is empty. This means that you did not properly install the SLING Python package either using pip3 or setup.sh. The reason that you do not get a `ModuleNotFoundError` is probably because there is a sling subdirectory in the directory where you are running.

You can check if the sling package is installed with this command:
```
sudo pip3 list | grep sling
```
It should output:
```
sling (2.0.0)
```
Also, If it is installed correctly, `import sling; print(sling.__path__)` should output something like `['/usr/lib/python3/dist-packages/sling']`.

**Comment by chingting** [comment]
It did output sling (2.0.0) but when I did print(sling.__path__), the error
said, AttributeError: module 'sling' has no attribute '__path__'

I attached a photo below, My sling folder is not empty, but there's another
sling folder in it. Thank you for all the help :)

Ellen

**Comment by ringgaard** [comment]
> It did output sling (2.0.0) but when I did `print(sling.__path__)`, the error said, `AttributeError: module 'sling' has no attribute '__path__'`

Hmm, this is weird. You earlier said that `print(vars(sling))` gave the following output:
```
{
  '__name__': 'sling', 
  '__doc__': None, 
  '__package__': 'sling',
  '__loader__': <_frozen_importlib_external._NamespaceLoader object at 0x7f90bed0c7f0>, 
  '__spec__': ModuleSpec(name='sling',
                         loader=<_frozen_importlib_external._NamespaceLoader object at 0x7f90bed0c7f0>,
                         submodule_search_locations=_NamespacePath(['/home/ellen/sling'])),
  '__file__': None, 
  '__path__': _NamespacePath(['/home/ellen/sling'])
}
```

This indicates that the sling object should have a `__path__` attribute

> I attached a photo below, My sling folder is not empty, but there's another sling folder in it. 

I doesn't look like your photo made it through github :(

From the information you have given, I assume that your current directory is your home directory (`/home/ellen`) and you have cloned the SLING git repo into `/home/ellen/sling`.

I am not sure what is going on with your machine but here is a list of things to check:

Make sure you are using Python 3:
```
$ python3 --version
Python 3.6.7
```
Check where the SLING Python package is installed:
```
$ sudo -H pip3 show sling
Name: sling
Version: 2.0.0
Summary: SLING frame semantic parsing framework
Home-page: https://github.com/google/sling
Author: Google
Author-email: sling-team@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: 
```
This shows that the location of the package is `/usr/local/lib/python3.6/dist-packages`.

Check that the SLING Pyton files are in the package directory:
```
$ ls -l /usr/local/lib/python3.6/dist-packages/sling
total 5256
-rw-r--r-- 1 root root    2508 May 19 18:33 flags.py
-rw-r--r-- 1 root root     630 May 19 18:33 __init__.py
-rw-r--r-- 1 root root    1033 May 19 18:33 log.py
drwxr-xr-x 3 root root    4096 May 19 18:33 myelin
drwxr-xr-x 3 root root    4096 May 19 18:33 nlp
drwxr-xr-x 2 root root    4096 May 19 18:33 __pycache__
-rwxr-xr-x 1 root root 5352128 May 19 18:33 pysling.so
drwxr-xr-x 3 root root    4096 May 19 18:33 task
```

Check that the package location is in the Python search path:
```
$ python3 -c 'import sys; print(sys.path)' 
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']
```
If all this is set up correctly on your machine, I don't know why you cannot import it.

**Comment by chingting** [comment]
Hi! Here's my result and I think it's all set up.

$ python3 --version

Python 3.7.0


$ sudo -H pip3 show sling

Metadata-Version: 2.0
Name: sling
Version: 2.0.0
Summary: SLING frame semantic parsing framework
Home-page: https://github.com/google/sling
Author: Google
Author-email: sling-team@google.com
Installer: pip
License: Apache 2.0
Location: /usr/local/lib/python3.5/dist-packages
Requires:
Classifiers:
  Programming Language :: Python
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.5


$ ls -l /usr/local/lib/python3.6/dist-packages/sling

total 5232
-rw-r--r-- 1 root staff    2508  五  16 11:05 flags.py
-rw-r--r-- 1 root staff     630  五  16 11:05 __init__.py
-rw-r--r-- 1 root staff    1033  五  16 11:05 log.py
drwxr-sr-x 3 root staff    4096  五  16 11:05 myelin
drwxr-sr-x 3 root staff    4096  五  16 11:05 nlp
drwxr-sr-x 2 root staff    4096  五  16 11:05 __pycache__
-rwxr-xr-x 1 root staff 5328576  五  16 11:05 pysling.so
drwxr-sr-x 3 root staff    4096  五  16 11:05 task


$ python3 -c 'import sys; print(sys.path)'

['', '/home/ellen/anaconda3/lib/python37.zip',
'/home/ellen/anaconda3/lib/python3.7',
'/home/ellen/anaconda3/lib/python3.7/lib-dynload',
'/home/ellen/anaconda3/lib/python3.7/site-packages']


I found my sys.path look different than yours, will that be the reason
that I couldn't run? Thank you :)

Ellen

**Comment by ringgaard** [comment]
There seems to be two problems that could explain why it doesn't work for you. First, you have installed the Python 3.5 package, but you are using Python 3.7. Secondly, your search path only includes per-user package paths. 

In PR #378, I have tried to consolidate the SLING Python wheels, so we can use the same wheel for all the supported version of Python 3 (3.5, 3.6, and 3.7). You can try to install it locally by doing:
```
pip3 install http://www.jbox.dk/sling/sling-2.0.0-py3-none-linux_x86_64.whl
```

**Comment by chingting** [comment]
I've just installed the wheel on my virtual machine and still got this
error AttributeError: module 'sling' has no attribute 'Parser'.
Do you have other suggestions that I should remove and uninstall something?
Thanks :)

Ellen

**Comment by ringgaard** [comment]
You basically just need to ensure that the installed SLING package is in your Python package search path, i.e. `sys.path`.

**Comment by chingting** [comment]
Hi!

After doing this, I am able to run the code:

sudo -H pip3 install --prefix /usr/local
http://www.jbox.dk/sling/sling-2.0.0-py3-none-linux_x86_64.whl

Ellen

**Comment by brendasalenave** [comment]
What if I want to apply the parser in a language other than English? For example, to process a sentence in Spanish, could I also use the Caspar model? Or would it be necessary to go the wiki data path? I have already tested with the parser example provided in the install guide just inputting a Spanish test; however I am not sure if it is parsing based on the English (I assume that is the default language), somehow correctly doing in the right way by detecting the language or what. It is not completely clear to me.

**Comment by ringgaard** [comment]
Using a parser trained in English to parse Spanish text is not going to work well. The CASPAR model is trained on PropBank, and as far as I know, it only exists in English. I have a pipeline for generating synthetic data from Wikipedia, but this is still in experimental mode and work in progress. I have only tried the Wikipedia corpus pipeline for English, but at least in theory it should work for Spanish as well.

**Comment by brendasalenave** [comment]
And when executing such pipeline how do you perform the parsing task in Python? Could you provide an example?
Sorry for the questions at this level, I'm still at the beginning of the study of this tool.

**Comment by ringgaard** [comment]
The parser models trained on silver-annotated data as used in the same way as the CASPAR parser although out outputs somewhat different annotations. The CASPAR parser outputs PropBank annotations, whereas the parsers trained on silver-data outputs annotations in Wikidata frame format.
```
import sling

parser = sling.Parser("myparser.flow")

text = input("text: ")
doc = parser.parse(text)
print(doc.frame.data(pretty=True))
for m in doc.mentions:
  print("mention", doc.phrase(m.begin, m.end))
```
