### ISSUE TITLE
parameter "closure" not respected for date values

### ISSUE THREAD

**Issue by anders-sandholm** [google/sling#347]
For Date targets in the call at https://github.com/google/sling/blob/6b0cde77e420f986bb6b9b4389ee94b479439c20/sling/nlp/wikicat/fact_matcher.py#L154 
we get the closure of the date in spite of closure = False.
E.g. calling with item Q20110226 and prop [P569], the call returns [Q2426, Q34644, Q6927] (year, decade, century) rather than just the actual date "19881219".
This means that fact matching stats for Category parses like "$date_of_birth=$year births" get (completely) messed up.

**Comment by rahul1980** [comment]
Thanks for pointing this out. I have fixed it in #348. The bug was introduced in #346.
The fix was tiny so I have taken the liberty to merge the PR.

**Comment by anders-sandholm** [comment]
Thanks for the fixes in #348 and #349.
