### ISSUE TITLE
Where to find pretrained sempar.flow

### ISSUE THREAD

**Issue by jayralencar** [google/sling#350]
Hi, this is more a question rather a issue.

I can't find sempar.flow file to download. Can someone help me?

**Comment by ringgaard** [comment]
We no longer actively support the old [sempar](http://www.jbox.dk/sling/sempar.flow) model, but you can find the caspar model [here](http://www.jbox.dk/sling/caspar.flow).

**Comment by jayralencar** [comment]
OK. Thank you.
