### ISSUE TITLE
version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by omerarshad** [google/sling#360]
python 2.7
gcc 4.8.5

got this error.

Traceback (most recent call last):
  File "sling_run.py", line 1, in <module>
    import sling
  File "/home/omer/.local/lib/python2.7/site-packages/sling/__init__.py", line 1, in <module>
    import sling.pysling as api
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/omer/.local/lib/python2.7/site-packages/sling/pysling.so)

**Comment by ringgaard** [comment]
Are you using Ubuntu 16.04?

**Comment by omerarshad** [comment]
yes

**Comment by ringgaard** [comment]
Did you build pysling.so from source or did you install if from the wheel using pip?

**Comment by omerarshad** [comment]
used this link to install from wheel 

sudo pip install http://www.jbox.dk/sling/sling-2.0.0-cp27-none-linux_x86_64.whl

then 

wget http://www.jbox.dk/sling/caspar.flow

You can then use the parser in Python:

import sling

parser = sling.Parser("caspar.flow")

text = raw_input("text: ")
doc = parser.parse(text)
print doc.frame.data(pretty=True)
for m in doc.mentions:
  print "mention", doc.phrase(m.begin, m.end)

**Comment by ringgaard** [comment]
It looks like sling-2.0.0-cp27-none-linux_x86_64.whl was built on an Ubuntu 18.04 machine. I have built it again on an Ubuntu 16.04 machine and redeployed it. Please try to install it again using pip and see if it works now.
```
sudo pip install -U http://www.jbox.dk/sling/sling-2.0.0-cp27-none-linux_x86_64.whl
```

**Comment by omerarshad** [comment]
yes it worked now, thanks
