### ISSUE TITLE
How to parse and get names of predicate

### ISSUE THREAD

**Issue by omerarshad** [google/sling#362]
having following output, how to parse it to get ARG0 and name of each predicate

[{=#1 :/pb/predicate /pb/ARG1: {=#2 :/pb/predicate /pb/ARG0: {=#3 :/pb/predicate}} /pb/ARG2: {=#4 :thing}}]

**Comment by ringgaard** [comment]
You can use the [Python SLING API](https://github.com/google/sling/blob/master/doc/guide/pyapi.md) to read the annotations, e.g.:
```
for mention in doc.mentions:
  for f in mention.evokes:
    for agent in f("/pb/ARG0"):
      print agent
```

**Comment by omerarshad** [comment]
it just prints /pb/predicate , whereas i would like to print its name.. is it possible?

**Comment by ringgaard** [comment]
What do you mean by "name"?

**Comment by omerarshad** [comment]
{=#1 :/pb/predicate /pb/ARG1: {=#2 :thing}}

how to check if a given frame is predicate or not?

**Comment by ringgaard** [comment]
You can check the type with the isa method:
```
f.isa("/pb/predicate")
```
