### ISSUE TITLE
On which corpus is NER trained?

### ISSUE THREAD

**Issue by omerarshad** [google/sling#363]

**Comment by ringgaard** [comment]
For the caspar model, the NER labels come from OntoNotes, which means that they are severely incomplete.

**Comment by omerarshad** [comment]
how to improve NER module only?

**Comment by ringgaard** [comment]
Get better NER labels :)

**Comment by johndpope** [comment]
(Distantly) Related - https://github.com/Franck-Dernoncourt/NeuroNER/issues/115
