### ISSUE TITLE
Example of how to train on our own dataset

### ISSUE THREAD

**Issue by omerarshad** [google/sling#371]
any detailed example on how to fine tune "caspar.flow" model on our own dataset?

**Comment by rahul1980** [comment]
At this moment, we don't have support to load a pre-trained model and resume training with it.
Note that even if we did, there is a subtle issue here: 
The pre-trained model comes with its commons store and action table, and if the fine-tuning corpus has symbols/actions outside those store/action-table then those will cause issues (crashes or exceptions).
