### ISSUE TITLE
No able to parse example sentence

### ISSUE THREAD

**Issue by vidhishanair** [google/sling#381]
Hi,
I'm wanted to try out the parser before building the source code. I followed the "Trying out the parser" section of install and build. 

I have installed pre-built wheel and model in my user folder in an Anaconda environment. For any text I try to provide, I get an empty parser document with no mentions. What am I doing wrong?

`Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sling
>>> parser = sling.Parser("caspar.flow")
>>> text = input("text: John loves Mary")
text: John loves Mary
>>> doc = parser.parse(text)
>>> print(doc.frame.data(pretty=True))
{=#1
  :document
  text: ""
  tokens: []
}
>>> for m in doc.mentions:
...   print("mention", doc.phrase(m.begin, m.end))
...
>>> text = input("John loves Mary")
John loves Mary
>>> print(doc.frame.data(pretty=True))
{=#1
  :document
  text: ""
  tokens: []
}
>>> text = input("text: Five Nights at Freddy's (often abbreviated to FNaF) is a media franchise based around an indie video game series created, designed, developed, and published by Scott Cawthon for Microsoft Windows, iOS, and Android.")
text: Five Nights at Freddy's (often abbreviated to FNaF) is a media franchise based around an indie video game series created, designed, developed, and published by Scott Cawthon for Microsoft Windows, iOS, and Android.
>>> doc = parser.parse(text)
>>> print(doc.frame.data(pretty=True))
{=#1
  :document
  text: ""
  tokens: []
}`

The output from print(vars(sling)) is below:

`{'__name__': 'sling', '__doc__': None, '__package__': 'sling', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7fdc7194feb8>, '__spec__': ModuleSpec(name='sling', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fdc7194feb8>, origin='/usr1/public/vbalacha/.conda/sling/lib/python3.6/site-packages/sling/__init__.py', submodule_search_locations=['/usr1/public/vbalacha/.conda/sling/lib/python3.6/site-packages/sling']), '__path__': ['/usr1/public/vbalacha/.conda/sling/lib/python3.6/site-packages/sling'], '__file__': '/usr1/public/vbalacha/.conda/sling/lib/python3.6/site-packages/sling/__init__.py', '__cached__': '/usr1/public/vbalacha/.conda/sling/lib/python3.6/site-packages/sling/__pycache__/__init__.cpython-36.pyc', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'callable': <built-in function callable>, 'chr': <built-in function chr>, 'compile': <built-in function compile>, 'delattr': <built-in function delattr>, 'dir': <built-in function dir>, 'divmod': <built-in function divmod>, 'eval': <built-in function eval>, 'exec': <built-in function exec>, 'format': <built-in function format>, 'getattr': <built-in function getattr>, 'globals': <built-in function globals>, 'hasattr': <built-in function hasattr>, 'hash': <built-in function hash>, 'hex': <built-in function hex>, 'id': <built-in function id>, 'input': <built-in function input>, 'isinstance': <built-in function isinstance>, 'issubclass': <built-in function issubclass>, 'iter': <built-in function iter>, 'len': <built-in function len>, 'locals': <built-in function locals>, 'max': <built-in function max>, 'min': <built-in function min>, 'next': <built-in function next>, 'oct': <built-in function oct>, 'ord': <built-in function ord>, 'pow': <built-in function pow>, 'print': <built-in function print>, 'repr': <built-in function repr>, 'round': <built-in function round>, 'setattr': <built-in function setattr>, 'sorted': <built-in function sorted>, 'sum': <built-in function sum>, 'vars': <built-in function vars>, 'None': None, 'Ellipsis': Ellipsis, 'NotImplemented': NotImplemented, 'False': False, 'True': True, 'bool': <class 'bool'>, 'memoryview': <class 'memoryview'>, 'bytearray': <class 'bytearray'>, 'bytes': <class 'bytes'>, 'classmethod': <class 'classmethod'>, 'complex': <class 'complex'>, 'dict': <class 'dict'>, 'enumerate': <class 'enumerate'>, 'filter': <class 'filter'>, 'float': <class 'float'>, 'frozenset': <class 'frozenset'>, 'property': <class 'property'>, 'int': <class 'int'>, 'list': <class 'list'>, 'map': <class 'map'>, 'object': <class 'object'>, 'range': <class 'range'>, 'reversed': <class 'reversed'>, 'set': <class 'set'>, 'slice': <class 'slice'>, 'staticmethod': <class 'staticmethod'>, 'str': <class 'str'>, 'super': <class 'super'>, 'tuple': <class 'tuple'>, 'type': <class 'type'>, 'zip': <class 'zip'>, '__debug__': True, 'BaseException': <class 'BaseException'>, 'Exception': <class 'Exception'>, 'TypeError': <class 'TypeError'>, 'StopAsyncIteration': <class 'StopAsyncIteration'>, 'StopIteration': <class 'StopIteration'>, 'GeneratorExit': <class 'GeneratorExit'>, 'SystemExit': <class 'SystemExit'>, 'KeyboardInterrupt': <class 'KeyboardInterrupt'>, 'ImportError': <class 'ImportError'>, 'ModuleNotFoundError': <class 'ModuleNotFoundError'>, 'OSError': <class 'OSError'>, 'EnvironmentError': <class 'OSError'>, 'IOError': <class 'OSError'>, 'EOFError': <class 'EOFError'>, 'RuntimeError': <class 'RuntimeError'>, 'RecursionError': <class 'RecursionError'>, 'NotImplementedError': <class 'NotImplementedError'>, 'NameError': <class 'NameError'>, 'UnboundLocalError': <class 'UnboundLocalError'>, 'AttributeError': <class 'AttributeError'>, 'SyntaxError': <class 'SyntaxError'>, 'IndentationError': <class 'IndentationError'>, 'TabError': <class 'TabError'>, 'LookupError': <class 'LookupError'>, 'IndexError': <class 'IndexError'>, 'KeyError': <class 'KeyError'>, 'ValueError': <class 'ValueError'>, 'UnicodeError': <class 'UnicodeError'>, 'UnicodeEncodeError': <class 'UnicodeEncodeError'>, 'UnicodeDecodeError': <class 'UnicodeDecodeError'>, 'UnicodeTranslateError': <class 'UnicodeTranslateError'>, 'AssertionError': <class 'AssertionError'>, 'ArithmeticError': <class 'ArithmeticError'>, 'FloatingPointError': <class 'FloatingPointError'>, 'OverflowError': <class 'OverflowError'>, 'ZeroDivisionError': <class 'ZeroDivisionError'>, 'SystemError': <class 'SystemError'>, 'ReferenceError': <class 'ReferenceError'>, 'BufferError': <class 'BufferError'>, 'MemoryError': <class 'MemoryError'>, 'Warning': <class 'Warning'>, 'UserWarning': <class 'UserWarning'>, 'DeprecationWarning': <class 'DeprecationWarning'>, 'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>, 'SyntaxWarning': <class 'SyntaxWarning'>, 'RuntimeWarning': <class 'RuntimeWarning'>, 'FutureWarning': <class 'FutureWarning'>, 'ImportWarning': <class 'ImportWarning'>, 'UnicodeWarning': <class 'UnicodeWarning'>, 'BytesWarning': <class 'BytesWarning'>, 'ResourceWarning': <class 'ResourceWarning'>, 'ConnectionError': <class 'ConnectionError'>, 'BlockingIOError': <class 'BlockingIOError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'ChildProcessError': <class 'ChildProcessError'>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, 'ConnectionRefusedError': <class 'ConnectionRefusedError'>, 'ConnectionResetError': <class 'ConnectionResetError'>, 'FileExistsError': <class 'FileExistsError'>, 'FileNotFoundError': <class 'FileNotFoundError'>, 'IsADirectoryError': <class 'IsADirectoryError'>, 'NotADirectoryError': <class 'NotADirectoryError'>, 'InterruptedError': <class 'InterruptedError'>, 'PermissionError': <class 'PermissionError'>, 'ProcessLookupError': <class 'ProcessLookupError'>, 'TimeoutError': <class 'TimeoutError'>, 'open': <built-in function open>, 'quit': Use quit() or Ctrl-D (i.e. EOF) to exit, 'exit': Use exit() or Ctrl-D (i.e. EOF) to exit, 'copyright': Copyright (c) 2001-2018 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved., 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information., 'license': Type license() to see the full license text, 'help': Type help() for interactive help, or help(object) for help about object.}, 'pysling': <module 'sling.pysling' from '/usr1/public/vbalacha/.conda/sling/lib/python3.6/site-packages/sling/pysling.so'>, 'api': <module 'sling.pysling' from '/usr1/public/vbalacha/.conda/sling/lib/python3.6/site-packages/sling/pysling.so'>, 'log': <module 'sling.log' from '/usr1/public/vbalacha/.conda/sling/lib/python3.6/site-packages/sling/log.py'>, 'inspect': <module 'inspect' from '/usr1/public/vbalacha/.conda/sling/lib/python3.6/inspect.py'>, 'os': <module 'os' from '/usr1/public/vbalacha/.conda/sling/lib/python3.6/os.py'>, 'INFO': 0, 'WARNING': 1, 'ERROR': 2, 'FATAL': 3, 'info': <function info at 0x7fdc6fecc8c8>, 'warning': <function warning at 0x7fdc6fecc950>, 'error': <function error at 0x7fdc6fecc9d8>, 'fatal': <function fatal at 0x7fdc6fecca60>, 'nlp': <module 'sling.nlp' from '/usr1/public/vbalacha/.conda/sling/lib/python3.6/site-packages/sling/nlp/__init__.py'>, 'sling': <module 'sling' from '/usr1/public/vbalacha/.conda/sling/lib/python3.6/site-packages/sling/__init__.py'>, 'NO_BREAK': 0, 'SPACE_BREAK': 1, 'LINE_BREAK': 2, 'SENTENCE_BREAK': 3, 'PARAGRAPH_BREAK': 4, 'SECTION_BREAK': 5, 'CHAPTER_BREAK': 6, 'DocumentSchema': <class 'sling.nlp.document.DocumentSchema'>, 'Token': <class 'sling.nlp.document.Token'>, 'Mention': <class 'sling.nlp.document.Mention'>, 'Document': <class 'sling.nlp.document.Document'>, 'Corpus': <class 'sling.nlp.document.Corpus'>, 'evaluate_frames': <built-in function evaluate_frames>, 'tokenizer': None, 'tokenize': <function tokenize at 0x7fdc6fed4378>, 'lex': <function lex at 0x7fdc6fed4400>, 'Parser': <class 'sling.nlp.parser.Parser'>, 'Store': <class 'sling.Store'>, 'Frame': <class 'sling.Frame'>, 'Array': <class 'sling.Array'>, 'RecordReader': <class 'sling.RecordReader'>, 'RecordDatabase': <class 'sling.RecordDatabase'>, 'RecordWriter': <class 'sling.RecordWriter'>, 'PhraseTable': <class 'sling.api.PhraseTable'>, 'Calendar': <class 'sling.Calendar'>, 'Date': <class 'sling.Date'>, 'WikiConverter': <class 'sling.WikiConverter'>, 'FactExtractor': <class 'sling.FactExtractor'>, 'MILLENNIUM': 1, 'CENTURY': 2, 'DECADE': 3, 'YEAR': 4, 'MONTH': 5, 'DAY': 6, 'CASE_INVALID': -1, 'CASE_NONE': 0, 'CASE_UPPER': 1, 'CASE_LOWER': 2, 'CASE_TITLE': 3}`

**Comment by vidhishanair** [comment]
Figured out my mistake!

**Comment by DebanjanaKar** [comment]
@vidhishanair, I'm getting the same error. Can you please tell me where I'm going wrong?
