### ISSUE TITLE
Guidance for custom wikipedia workflow

### ISSUE THREAD

**Issue by vidhishanair** [google/sling#384]
Hi,
I'm looking to parse a lot of text, to extract mentions and their links to wikidata, similar to the wikipedia+wikidata workflow. I tried to naively replace the wikipedia input corpus with my own corpus in the same format, but this didn't result to much. I see that my data is being read and is present in the articles-00007-of-000010.rec file, but the parsed text doesn't come up in documents.rec or any downstream sections of the workflow.

Could you guide me if there is a better way to do so?

**Comment by yuchenlin** [comment]
Having the same question...

**Comment by ringgaard** [comment]
Could you be more specific? Do you want to run the silver annotation pipeline on some text? We use the silver annotation pipeline for generating training data for our parser training.

**Comment by yuchenlin** [comment]
Hi @ringgaard ,  I want to use SLING as an entity linker on my own raw text. I am setting up the wikidata and wikipedia following this [instruction](https://github.com/google/sling/blob/master/doc/guide/wikiflow.md). (in the import-wikidata stage now). 
I was wondering if I could simply use SLING python-api like [this](https://github.com/google/sling/blob/master/doc/guide/install.md#python) to tag any raw sentence that I have.

**Comment by ringgaard** [comment]
The silver annotation pipeline, which is currently doing the entity linking, uses the DocumentAnnotation class, which is not exposed in the Python API. However, it would be useful to have a Python API for this. Let me give it a shot, and get back to you with a status update on this.

**Comment by yuchenlin** [comment]
Thanks very much! I can also call c++ functions or use command lines. Is there an example of parsing raw text with Wikidata frames for entity linking? Thanks!

**Comment by ringgaard** [comment]
I have submitted #442 for review. This allows you to run the silver annotation pipeline from Python. Please notice that the output of the silver annotation is pretty noisy, so it is best used as training data for a machine-learned system that can generalize from noisy training data.

You need to build the IDF table first with the following command:
```
./run.sh --build_idf
```

**Comment by yuchenlin** [comment]
Hi @ringgaard, thank you very much for the help! Will have a try!
