### ISSUE TITLE
Could the training data of 'caspar.flow' be released?

### ISSUE THREAD

**Issue by tangg555** [google/sling#399]
I cannot find any ready-made dataset to train a semantic parser. I don't make sure whether I didn't search in a right place or it is unavailable.

If the dataset is unavailable, please let me know, thank you.:-)

**Comment by rahul1980** [comment]
The model was trained on the Ontonotes version 5 corpus. That corpus is not freely available though. If you have access to it, you can prepare it for training via [this script](https://github.com/google/sling/blob/1edcf386fd921ca4d85267ef2c469bc8650eb7ba/sling/nlp/parser/ontonotes/make_corpus.sh).

**Comment by tangg555** [comment]
OK, thank you for your reply. :-)
