### ISSUE TITLE
Problem converting Ontonotes corpus to SLING

### ISSUE THREAD

**Issue by lenyabloko** [google/sling#404]
Connecting to conll.cemantix.org (conll.cemantix.org)|66.147.244.155|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9912 (9.7K)
Saving to: ‘dev.ids’

dev.ids                      100%[=============================================>]   9.68K  --.-KB/s    in 0s      

2019-08-14 02:25:53 (184 MB/s) - ‘dev.ids’ saved [9912/9912]

--2019-08-14 02:25:53--  http://conll.cemantix.org/2012/download/ids/english/coref/test.id
Resolving conll.cemantix.org (conll.cemantix.org)... 66.147.244.155
Connecting to conll.cemantix.org (conll.cemantix.org)|66.147.244.155|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9912 (9.7K)
Saving to: ‘test.ids’

test.ids                     100%[=============================================>]   9.68K  --.-KB/s    in 0s      

2019-08-14 02:25:54 (108 MB/s) - ‘test.ids’ saved [9912/9912]

--2019-08-14 02:25:54--  http://ontonotes.cemantix.org/download/conll-formatted-ontonotes-5.0-scripts.tar.gz
Resolving ontonotes.cemantix.org (ontonotes.cemantix.org)... 66.147.244.155
Connecting to ontonotes.cemantix.org (ontonotes.cemantix.org)|66.147.244.155|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9241 (9.0K) [application/x-gzip]
Saving to: ‘conll-formatted-ontonotes-5.0-scripts.tar.gz’

conll-formatted-ontonotes-5. 100%[=============================================>]   9.02K  --.-KB/s    in 0s      

2019-08-14 02:25:54 (223 MB/s) - ‘conll-formatted-ontonotes-5.0-scripts.tar.gz’ saved [9241/9241]

Generate CoNLL files
----------------------------------------------------------------------------------------------------

could not find the gold parse [ontonotes-release-5.0/data/files/data/english/annotations/tc/ch/00/ch_0028.parse] in the ontonotes distribution ... exiting ...

----------------------------------------------------------------------------------------------------
~/sling
![Ontonotes](https://user-images.githubusercontent.com/55606/62993040-d8168c80-be23-11e9-8c70-0bb1b45c093c.PNG)

**Comment by ringgaard** [comment]
Do you have LDC2013T19.tar.gz in local/data/corpora/ontonotes? This is a LDC-licensed corpus which we cannot distribute, so you need to have a LDC license to build the SLING training corpus.

**Comment by lenyabloko** [comment]
I have registered with LDC using my institutional  email address. But I don't see any option for download.

**Comment by ringgaard** [comment]
As stated in [make_corpus.sh](https://github.com/google/sling/blob/master/sling/nlp/parser/ontonotes/make_corpus.sh#L17), you need to download LDC2013T19 from LDC yourself and put it in local/data/corpora/ontonotes.
