### ISSUE TITLE
/data/wiki/templates-en.sling: No such file or directory

### ISSUE THREAD

**Issue by dayihengliu** [google/sling#420]
During  ./run.sh --parse_wikipedia, I got the error /data/wiki/templates-en.sling: No such file or directory. Any suggestions?

**Comment by anders-sandholm** [comment]
Thanks @dayihengliu for filing the issue. The mentioned file was deleted/renamed in the repo recently and the scripts updated accordingly. Please make sure you have downloaded/merged the latest version of all files from github and see if that helps. Alternatively, try running with the --dryrun flag to get info on what files are needed/accessed.

**Comment by dayihengliu** [comment]
Thanks for your quick reply. I also want to know where can I find a usage example of python for the entity link.

**Comment by anders-sandholm** [comment]
Just wondering, did you get the initial issue resolved by re-merging from github?

Unfortunately, we don't have Python example code yet for using the entity resolver / linker, but please stay tuned for an update. We're considering to refactor the code in a way will make it a lot easier to generate data for the "ner" part of the flow and it should come with some easy-to-use example code as well. HTH.

**Comment by anders-sandholm** [comment]
Assuming the original error "/data/wiki/templates-en.sling: No such file or directory" got resolved.  Feel free to re-open that is not the case.
