### ISSUE TITLE
SLING for other languages

### ISSUE THREAD

**Issue by jayralencar** [google/sling#428]
Is it possible to train SLING with data from another language than English?

Did anybody ever try it?

**Comment by anders-sandholm** [comment]
Yes. There isn't much in SLING that inherently relies on training data being in English. In fact, the Wiki pipeline runs in 12 different languages and we're hoping to be training on silver-annotated Wikipedia articles across all 12 languages shortly. 

See e.g. slides or video from the recent WikidataCon presentation of SLING at https://www.wikidata.org/wiki/Wikidata:WikidataCon_2019/Program/Sessions/Wikidata_knowledge_base_completion_using_multilingual_Wikipedia_fact_extraction
