### ISSUE TITLE
SLING Frames - how can one retrieve multiple slot values?

### ISSUE THREAD

**Issue by krasi0** [google/sling#440]
I made the following schema:
```{=/entity :schema +named name: "Entity"}

{=/entity/classA :schema +/entity
    name: "Class A"
  
    role: {=/entity/hasProperty/color :slot
        target: string
        multi: 1
    }
}

{=/entity/objectA :/entity/classA
    /entity/hasProperty/color: "red"
    /entity/hasProperty/color: "green"
    /entity/hasProperty/color: "blue"
}
```
and am trying to access all the color values of objectA:
```std::cout << "Has property: " << objectAFrame.GetString("/entity/hasProperty/color") << std::endl;

const auto entityHasPropertyColorHandle = localStore.Lookup("/entity/hasProperty/color");
for (const auto& slot : objectAFrame) {
    if (slot.name == entityHasPropertyColorHandle) {
        std::cout << "Object A color: " << objectAFrame.GetString(slot.name) << std::endl;
    }
} ```

The above code only prints "red" 3 times. I am sure that there must be a way to access the "green" and "blue" values, too (analogically to accessing all child frames of Marge Simpson in the example). But how?

Also, how can I access the value of `multi` (which is defined as 1 in the schema above) of /entity/classA => slot /entity/hasProperty/color
The following code prints `0`:
```std::cout << "Color multi: " << objectAFrame.GetInt("/entity/hasProperty/color/multi") << std::endl;```

**Comment by rahul1980** [comment]
You can access multi-valued slots like:

for (const auto& slot : frame) {
   if (slot.name == entityhasPropertyColorHandle) {
     std::cout << Object(frame.store(), slot.value).AsString().value() << "\n";
   }
}
Note that GetString() (and other methods like that) only return the first value for the specified role, in this case "red".

This is much more compact in python:

for color in frame("/entity/hasProperty/color"):
   print color

**Comment by rahul1980** [comment]
Forgot to answer the other question:

You can do:
```
objectAFrame.GetFrame("isa").GetInt("multi");
```
This just means that you are accessing the (first) type of objectAFrame, and from that type, accessing the 'multi' field.

**Comment by krasi0** [comment]
@rahul1980 Thanks for your answers! 
The first answer is exactly what I needed.

I couldn't get the second one to work though:
```objectAFrame.GetFrame("isa").GetInt("multi");``` always returns 0
I believe that we should somehow involve the actual slot, since "multi" is a property of the `/entity/hasProperty/color` slot in the schema. So I tried both of the following options but in both cases, it seems like the executable gets into an infinite loop or something like that:
```const auto entityHasPropertyColorHandle = localStore.Lookup("/entity/hasProperty/color");
std::cout << "Color multi: " << objectAFrame.GetFrame(entityHasPropertyColorHandle).GetInt("multi") << std::endl;

std::cout << "Color multi: " << objectAFrame.GetFrame(entityHasPropertyColorHandle).GetFrame("isa").GetInt("multi") << std::endl;
```
Any suggestions?

**Comment by ringgaard** [comment]
You need to look up the multi property/role on the entityhasPropertyColorHandle frame:

```
Frame(store, entityhasPropertyColorHandle).GetInt("multi")
```

**Comment by krasi0** [comment]
That did it. Thanks!
