### ISSUE TITLE
Annotating data

### ISSUE THREAD

**Issue by JoshuaMathias** [google/sling#447]
Hi. Thank you for this project. 
I've looked through the guides and data on this repository, but have these questions:

1. Is there documentation on how to annotate data for SLING?
2. Is there an example file of annotated data on natural language text? If not, what example would you recommend looking at? 
3. Do you have any advice for manually annotating natural language text for use with SLING? I'm wondering if some other tool and format should be used first and then converted to SLING's format.

**Comment by ringgaard** [comment]
We haven't done any "native" manual annotation of SLING frame on document, but you can take a look [here](https://github.com/ringgaard/sling/blob/master/doc/guide/pyapi.md#documents) for a simple example of how to build an annotated document using the SLING Python API. You could also consider using the [LEX](https://github.com/ringgaard/sling/blob/master/doc/guide/pyapi.md#lex-format) format for manual annotation.
