### ISSUE TITLE
Python API for the tokenizer

### ISSUE THREAD

**Issue by JunjieHu** [google/sling#448]
Hi @ringgaard 

Is there any Python APIs for the text tokenizer?
For example, if we want to use your processed document for other downstream tasks, we want to use the same tokenizer as sling did for our testing data. Could you point me to some functions that I can use to tokenize text or linked entity in my text?

**Comment by ringgaard** [comment]
You can use the built-in tokenizer to tokenize text and turn it into a
document like this:
```
import sling
doc = sling.tokenize(text)
```

See also:
https://github.com/ringgaard/sling/blob/master/doc/guide/pyapi.md#parsing

**Comment by JunjieHu** [comment]
Perfect! That's what I need! Thanks!
May I know briefly what operations does the tokenizer do on the input text?
For example, convert "you're" to "you" and "'re".

**Comment by ringgaard** [comment]
The text tokenizer is compatible with Penn Treebank tokenization with some
LDC extensions, so clitics like [you're] are split into [you] and ['re].

**Comment by JunjieHu** [comment]
@ringgaard  Thanks for your pointer!
I have a follow-up question. How can we get the mentions for our own testing sentence that doesn't exist in the wikipedia articles?

For example, I try the following code, and find that doc.mentions is an empty list. Do you know how to get the correct mentions?
`
import sling

commons = sling.Store()
docschema = sling.DocumentSchema(commons)
commons.freeze()
store = sling.Store(commons)
text = "Barack Obama served as the 44th President of the United States."  # our own testing sentence
doc = sling.tokenize(text, store=store, schema=docschema) # doc.mentions is an empty list.
`

**Comment by ringgaard** [comment]
When you have tokenized the document, it only contains the text and the tokens. In order to get the mentions as well you need to run the semantic parser, see https://github.com/google/sling/blob/master/doc/guide/pyapi.md#parsing
