### ISSUE TITLE
problem about "sling fuse_items"

### ISSUE THREAD

**Issue by foolfun** [google/sling#449]
![image](https://user-images.githubusercontent.com/35558298/98912813-903c5480-2501-11eb-8a2f-08b8ac202d1e.png)

**Comment by foolfun** [comment]
When I ran the command "sling fuse_items" ，I met this problem， I have no idea how to solve it.

**Comment by foolfun** [comment]
I have no idea how to slove this problem

**Comment by ringgaard** [comment]
The SLING project has moved to [ringgaard/sling](https://github.com/ringgaard/sling). I would prefer if you used that repo instead, since the google/sling repo is no longer being maintained.

Could I get you to try the newest version on ringgaard/sling and see if the problem persists?
