### ISSUE TITLE
"decoder.cc:108] Invalid tag value: 87" when trying to parse corpus with Myelin-based tool

### ISSUE THREAD

**Issue by around1991** [google/sling#79]
Hi all

Thanks for releasing the parser! [original post out of date, please see the new comment below]

Thanks
Kris

**Comment by around1991** [comment]
Actually, I've just read the documentation a bit more - the corpus argument is expected to be a list of files, or a zip containing a list of files. I've now zipped up the contents of corpus/ to corpus.zip, and when I run bazel-bin/nlp/parser/tools/parse --logtostderr --parser=sempar.flow --corpus corpus/corpus.zip --parse I get the error in the title.

What should I be doing instead?

Thanks!
Kris

**Comment by ringgaard** [comment]
What is the format of your corpus? Is it just a bunch of text files? The file specified with the --corpus parameter expects the input files to be in encoded SLING format.

**Comment by around1991** [comment]
Ah, I see, thanks for the info. What's the recommended way for parsing a large collection of test documents then? Using the --text command line option?

**Comment by ringgaard** [comment]
The parse tool does not currently support parsing text files, but you can make your own program for doing this:

```c++
#include <iostream>
#include <string>

#include "base/init.h"
#include "file/file.h"
#include "frame/store.h"
#include "frame/serialization.h"
#include "nlp/document/document-tokenizer.h"
#include "nlp/parser/parser.h"

DEFINE_string(parser, "", "Input file with flow model");
DEFINE_string(input, "", "Input file");

using namespace sling;

int main(int argc, char *argv[]) {
  InitProgram(&argc, &argv);

  // Load parser.
  Store commons;
  sling::nlp::Parser parser;
  parser.Load(&commons, FLAGS_parser);
  commons.Freeze();

  // Create document tokenizer.
  sling::nlp::DocumentTokenizer tokenizer;

  // Read input document.
  string text;
  CHECK(File::ReadContents(FLAGS_input, &text));

  // Create frame store for document.
  sling::Store store(&commons);
  sling::nlp::Document document(&store);

  // Tokenize text.
  tokenizer.Tokenize(&document, text);

  // Parse document.
  parser.Parse(&document);
  document.Update();

  // Output document annotations.
  std::cout << sling::ToText(document.top(), 2);
}
```

You can use this BUILD rule:

```
cc_binary(
  name = "parse-text",
  srcs = ["parse-text.cc"],
  deps = [
    "//base",
    "//file:posix",
    "//frame:store",
    "//nlp/document",
    "//nlp/document:document-tokenizer",
    "//nlp/parser",
  ],
)
```

PS: I found a bug in the parser runtime that produces wrong parse results when parsing multiple sentences (see #80).

**Comment by around1991** [comment]
Great, thank you very much for providing that! I'll have a play around and see if it works better :)
