### ISSUE TITLE
Parser fails to identify coreference

### ISSUE THREAD

**Issue by around1991** [google/sling#81]
Hi guys

Sorry to be on an issue-opening spree, but I've been having a bit more of a play, and it seems SLING with the pre-trained sempar.flow file doesn't seem to recognise coreference at all. If you try to parse the sentence 'The dog who I loved died yesterday', it gets that there is a loving frame, and a dying frame, but it thinks that the arg-2 of the loving frame is 'who', and the arg-1 of the dying frame is 'dog', and these are assigned different mentions by the parser.

Is this intended behaviour?

Kris

**Comment by ringgaard** [comment]
While the parser can, at least in theory, predict coreference, the pre-trained model described in the paper does not include coreference information from OntoNotes. The REFER action can be used for re-evoking a existing frame, but we did not use this in the experiment. We could try to make a simple experiment to include the coref information from OntoNotes, but the limited size of the attention buffer could be a problem, so we are thinking about better ways to handle reference.
