### ISSUE TITLE
Parsing SLING output in Python

### ISSUE THREAD

**Issue by around1991** [google/sling#82]
Hi guys

One final question: is there a plan in the works to make the output of SLING easier to parse in Python? Naively, the output isn't JSON compatible (attribute names and values need to be double quoted), and I've tried to write a regex-based parser for SLING output, but it's a bit trickier than I'd like

Apologies for the spam!
Kris

**Comment by ringgaard** [comment]
The SLING parser is a C++ library, so we only have code for parsing SLING frames in C++. We only use Python for training with Tensorflow. We are working on a Python API for the parser and the frame stores.

**Comment by ringgaard** [comment]
I have submitted #107 that adds a Python API for the SLING frame store. You can use this by installing this wheel:
```
sudo pip install http://www.jbox.dk/sling/sling-1.0.0-cp27-none-linux_x86_64.whl
```
This allows you to load, store, and manipulate SLING frames in Python.

Creating a new global store:
```
import sling
commons = sling.Store()
```
Loading frames into the store:
```
commons.load("data/nlp/schemas/meta-schema.sling")
commons.load("data/nlp/schemas/document-schema.sling")
```
Loading binary encoded frames in legacy encoding:
```
actions = commons.load("local/sempar/out/table", binary=True)
```
Freezing a store to makes it read-only and allows local stores to be created based on the store:
```
commons.freeze()
```
Looking up frames in the store:
```
name = commons['name']
```
Create a local store:
```
store = sling.Store(commons)
```
Frames in the global store are now accessible from the local store:
```
doc = store['/s/document']
```
Role values for frames can be accessed as attributes:
```
print doc.name
```
or using indexing:
```
print doc['name']
```
You can also use a frame value to access roles:
```
print doc[name]
```
You can test if a frame has a role:
```
if 'name' in doc: print "doc has 'name'"
if name in doc: print "doc has name"
```
The `parse()` method can be used for adding new frames to the store:
```
f = store.parse('{a:10 b:10.5 c:"hello" d:{:/s/thing} e:[1,2,3]}')
```
The `frame()` method can be used to create a new frame from a dictionary:
```
f = store.frame({'a': 10, 'b': 10.5, 'c': "hello"})
```
or a list of slot tuples:
```
f = store.frame([('a', 10), ('b': 10.5), ('c': "hello")])
```
Slots can be added or modified using attribute assignment:
```
f.c = "hello world"
```
or using index assignment:
```
f[name] = "The F frame"
f['a'] = 20
```
New slots can be added using the `append()` method:
```
f.d.append(name, "A thing")
```
Multiple slot can be added using the `extend()` method:
```
f.extend({'foo': 10, 'bar': 20})
```
or using a list of slot tuples:
```
f.extend([('foo', 10), ('bar': 20)])
```
All the slots in a frame can be iterated:
```
for name, value in f:
  print "slot", name,"=", value
```
or just the roles with a particular name:
```
for r in doc('role'):
  print "doc role", r
```
Frames can be encoded in text format with the `data()` method:
```
print f.data()
```
and with indentation:
```
print f.data(pretty=True)
```
or with binary encoding:
```
print len(f.data(binary=True))
```
Arrays can be created with the `array()` method:
```
a = store.array([1, 2, 3])
```
Arrays can also be created with nil values that can be assigned later:
```
a = store.array(3)
a[0] = 1
a[1] = 2
a[2] = 3
```
SLING arrays works much in the same way as Python lists except that they have a fixed size:
```
print len(a)
print a[1]
for item in a: print item
```
Finally, a store can be save to a file in textual encoding:
```
store.save("/tmp/txt.sling")
```
or in binary encoding:
```
store.save("/tmp/bin.sling", binary=True)
```

**Comment by ringgaard** [comment]
With the Python SLING API, you can read the contents of a corpus file for the parser with this program:
```
import sling
import zipfile

corpus = zipfile.ZipFile("local/sempar/dev.zip", "r")
for f in corpus.infolist():
  doc = sling.Store().parse(corpus.read(f), binary=True)
  print doc.data(pretty=True)
corpus.close()
```

**Comment by bman7777** [comment]
I'm having a little trouble figuring out how to provide custom schema definitions.  If I try-

```
import sling
my_store = sling.Store()
my_store.load("custom-schema.sling")
parser = sling.Parser("sempar.flow", my_store)
doc = parser.parse(text)
```
I still see "saft" entities rather than my custom entities.  Any idea what I am missing?  

(FWIW my custom schema for testing purposes is a copy of https://github.com/google/sling/blob/caspar/sling/frame/README.md#toy-schema)

Thank you!

**Comment by ringgaard** [comment]
The frame schemas are stored in the sempar.flow file as a blob, so I think these might override your custom schemas.

**Comment by jackxpeng** [comment]
I followed the 12/8/2017 comment above but the saved text store "/tmp/txt.sling" is empty. Here is the code:

```
import sling
commons = sling.Store()
commons.load("data/nlp/schemas/meta-schema.sling")
commons.load("data/nlp/schemas/document-schema.sling")
#actions = commons.load("local/sempar/out/table", binary=True)
commons.freeze()
name = commons['name']
store = sling.Store(commons)
doc = store['/s/document']
a = store.array([1, 2, 3])
f = store.frame({'a': 10, 'b': 10.5, 'c': "hello"})
store.save("/tmp/txt.sling") 
```

**Comment by ringgaard** [comment]
The store.save() method only writes the frames in the symbol table, i.e. the frames with ids. If you assign an id to the frame, it should be saved, e.g.:
```
import sling
commons = sling.Store()
commons.freeze()
store = sling.Store(commons)
f = store.frame({'id': 'xxx', 'a': 10, 'b': 10.5, 'c': "hello"})
store.save("/tmp/txt.sling") 
```

**Comment by jackxpeng** [comment]
Got it. Thanks, Michael.

**Comment by jackxpeng** [comment]
Is there a way to use python to save multiple frames in a recordio file for training CASPAR?

**Comment by jayralencar** [comment]
Hi,
How to parse the output to JSON?

**Comment by ringgaard** [comment]
I have sent out PR #352, which allows you to output SLING frames in JSON format. You should be aware that SLING frames are more general than JSON, so it will not always output "valid" JSON:

- JSON does not support references natively, so references are output using "$ref" slots. 
- In SLING, both the name and the value in a frame slot can be an arbitrary object, which is not allowed in JSON.
- SLING allows multiple slots to have the same name.

If you use SLING in Python, I would recommend using the SLING Python API for accessing the SLING frames to avoid too many surprises.

**Comment by anders-sandholm** [comment]
Fixed previously with the extended Python API and enhanced further with PR #352, which exposes JSON as an output option.

**Comment by jayralencar** [comment]
Thank you.
