### ISSUE TITLE
build error in mac os10.12.5

### ISSUE THREAD

**Issue by myboyliu** [google/sling#85]
(py2.7) ericliudeMacBook-Pro:sling ericliu$ bazel build -c opt nlp/parser nlp/parser/tools:all
INFO: Found 4 targets...
ERROR: /Users/ericliu/dlnlp/sling/frame/BUILD:30:1: C++ compilation of rule '//frame:object' failed (Exit 1).
In file included from frame/object.cc:15:
./frame/object.h:19:10: fatal error: 'hash_map' file not found
#include <hash_map>
         ^
1 error generated.
INFO: Elapsed time: 1.624s, Critical Path: 1.28s
(py2.7) ericliudeMacBook-Pro:sling ericliu$

**Comment by myboyliu** [comment]
./frame/object.h 
#include <ext/hash_map> can be compiled.

**Comment by myboyliu** [comment]
other errors has been occurred.

**Comment by ringgaard** [comment]
Seems like some work is needed if we want to be able to run SLING on MacOS. I don't have access to a build environment on MacOS, so I cannot help making it run on MacOS.

**Comment by vseledkin** [comment]
I was able to build sling on mac and the only thing i changed along with #include <hash_map> issue was 
change 
//if (fdatasync(fd_) != 0) return IOError(filename_, errno);   to  
 if (fcntl(fd_, F_FULLFSYNC) != 0) return IOError(filename_, errno);
 here
https://github.com/google/sling/blob/674c389b28da5617e6c2e325bca7feac31bd88e3/sling/file/posix.cc#L140

**Comment by ringgaard** [comment]
I have submitted #118 to fix the fdatasync and then hash_map issues on MacOS.
