### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by GMarzinotto** [google/sling#92]
Hello, this is more a question rather than an issue.

I downloaded the pre-trained model and I have been testing it.
I was wondering if this pre-trained model is the one you evaluate in the paper,
or if it is a toy model example.

Thank you very much,
Kind Regards!

**Comment by ringgaard** [comment]
The pretrained model should be the same as the one we used for the experiment in the paper.

**Comment by GMarzinotto** [comment]
Great, thank you for the fast answer!
