### ISSUE TITLE
Check failed: input_->ReadVarint64(&tag)

### ISSUE THREAD

**Issue by yiqiyu** [google/sling#96]
There's one weird problem.
I tried to train a model with my own zip corpora but I got this message when running the script:

`

    INFO: Build completed successfully, 1 total action
    F1123 17:51:04.615497 15134 decoder.cc:45] Check failed: input_->ReadVarint64(&tag) 

    *** Check failure stack trace: ***

    @           0x4dc49a  google::LogMessage::Fail()

    @           0x4dd1aa  google::LogMessage::SendToLog()

    @           0x4dc1c5  google::LogMessage::Flush()

    @           0x4dda99  google::LogMessageFatal::~LogMessageFatal()

    @           0x426b29  sling::Decoder::DecodeObject()

    @           0x426f35  sling::Decoder::Decode()

    @           0x426050  sling::nlp::DocumentSource::Next()

    @           0x40b2e8  OutputActionTable()

    @           0x407426  main

    @     0x7fe1a36fd830  __libc_start_main

    @           0x409669  _start

`
The weird part is that after I unzipped and then zipped again the corpora from conll and ran the script with these rezipped corpora, same message showed up.

Thanks for any help!

**Comment by ringgaard** [comment]
Could this be because your zip file contains SLING documents in text format instead of binary encoded SLING format? The parser currently assumes that the frames are in binary format.

**Comment by yiqiyu** [comment]
It works now. Many thanks!
